### ISSUE TITLE
For gcp-app:start write devappserver output to a file

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/app-maven-plugin#10]

**Comment by loosebazooka** [comment]
This is obselete now? Stream listeners die if we try this. @meltsufin

**Comment by meltsufin** [comment]
Weren't we looking to do this as the jetty level somehow?

**Comment by loosebazooka** [comment]
I wasn't sure what the context of this bug was

**Comment by loosebazooka** [comment]
I mean at our level or the devappsever.py level

**Comment by meltsufin** [comment]
Regardless of where the fix will come from, we should track it here also.

**Comment by patflynn** [comment]
@meltsufin @loosebazooka status?

**Comment by loosebazooka** [comment]
@TadCordle maybe we should do this, it's in the appengine gradle plugin
https://github.com/GoogleCloudPlatform/app-gradle-plugin/pull/156
