### ISSUE TITLE
Rename repo appengine-maven-plugin

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/app-maven-plugin#105]
For SEO and discoverability

**Comment by meltsufin** [comment]
We can't do it until, the old appengine-maven-plugin is completely removed.

**Comment by elharo** [comment]
Didn't realize that was using the same URL. But we don't have to wait for
that to go away we can rename that legacy-appengine-maven-plugin or some
such and then use the name for the new plugin.

--
Elliotte Rusty Harold
on a mobile phone so please excuse weird autocorrects

**Comment by patflynn** [comment]
I wouldn't be surprised if those urls are not reassignable.  Typically when
you rename a repository github setups up the old name to redirect to the
new one.
