### ISSUE TITLE
Does this maven plugin support multi-module projects?

### ISSUE THREAD

**Issue by aleemstreak** [GoogleCloudPlatform/app-maven-plugin#108]
We have a mix of standard and flex modules, does this plugin support getting the gcloud dev server started with all the modules running?

**Comment by meltsufin** [comment]
Does #82 help?

**Comment by patflynn** [comment]
@aleemstreak I'm assuming that you've been able to run multi-modules with @meltsufin's suggestion. Please feel free to re-open if that's not the case.
