### ISSUE TITLE
Release 1.1.0-beta with repo source context goal

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/app-maven-plugin#111]
First we need to change the version in the trunk to 1.1.0-beta-SNAPSHOT and release 1.1.0-beta from there.

@joaoandremartins Can you take this on?

**Comment by patflynn** [comment]
@joaoandremartins @meltsufin If you guys could do this today that would be awesome!  It would make my life easier for the presentation next week.

**Comment by joaoandremartins** [comment]
OK, I'm now waiting for reviews on https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1085 so should be able to tackle this now.
