### ISSUE TITLE
Endpoints app doesn't work after deployment

### ISSUE THREAD

**Issue by bradfriedman** [GoogleCloudPlatform/app-maven-plugin#115]
Trying to deploy an Endpoints app using the plugin, the deployment hung for about 25 minutes on the GCLOUD step, then finally "succeeded." That seems like a problem in and of itself, especially since the old plugin completes in about 3.5 minutes.

However, after sending traffic to the app, it returned a 502 Bad Gateway response code. This was the exact same app as the one I deployed using the old plugin. The only change in the deployment was moving the Dockerfile to the docker/ directory and calling `mvn appengine:deploy` instead of `mvn gcloud:deploy`.

**Comment by patflynn** [comment]
@bradfriedman
Endpoints framework support is being moved into its own plugin. 
https://github.com/GoogleCloudPlatform/endpoints-framework-maven-plugin.  It's very early at this point. @loosebazooka should know if it's usable.

**Comment by loosebazooka** [comment]
Right, but the new plugin shouldn't be required for uploading the app. The only difference is now we don't auto-inject the service classes into the web.xml (which I believe is in line with the error).

You should notice some difference in the web.xml is your target directory between what the old plugin was doing and what the new plugin is doing

old plugin would have done some magic to add in these extra lines into your web.xml
````xml
<servlet>
    <servlet-name>SystemServiceServlet</servlet-name>
    <servlet-class>com.google.api.server.spi.SystemServiceServlet</servlet-class>
    <init-param>
        <param-name>services</param-name>
        <param-value>com.whatever.endpoint1, com.whatever.endpoint2</param-value>
    </init-param>
</servlet>
<servlet-mapping>
    <servlet-name>SystemServiceServlet</servlet-name>
    <url-pattern>/_ah/spi/*</url-pattern> <!-- or /_ah/api/* if you're using the new framework -->
</servlet-mapping>
````

you just need to change the `<param-value>` to your endpoint classes

**Comment by patflynn** [comment]
@bradfriedman @loosebazooka did this fix the issue?
