### ISSUE TITLE
need earlier config error detection for standard apps not having appengine-web.xml

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/app-maven-plugin#116]
Now that the Maven plugin supports both Flex and Standard, it might be confusing to move back and forth between a Flex runtime (that needs an app.yaml) and a Standard runtime (Java7 or coming Java8).
If the user just adds runtime:java7 in the app.yaml, it does not work for Standard which currently mandates an appengine-web.xml used by the prod runtime...

It would be nice to detect early this configuration error in the plugin (and Gradle And intellig): Standard (i.e no vm:true nor env:flex) should not be currently defined via app.yaml but with an appengine-web.xml

Medium term, they are discussions about opening support for non staging phase in standard and use user defined app.yaml, but this is not currently what the product does or what is documented, so we should add the check in the new plugins....
Now, it might be complicated to detected a generated app.yaml via staging compared to a user provided app.yaml, but it can be done (the old gcloud plugin had some logic there already)

**Comment by patflynn** [comment]
@ludoch could you describe the exact condition you want to generate an error on?  

We should make sure that the documentation for standard speaks only in terms of the appengine-web.xml (which I think it currently does)

**Comment by patflynn** [comment]
OK so this bug is basically that the user should not be able to provide their own app.yaml that specifies a java standard runtime.  Standard deployment only accepts appengine-web.xml in the contract.   

This may be fixed by moving staging into gcloud.

**Comment by patflynn** [comment]
If a user specifies a java7 standard runtime manually in app.yaml and uses gcloud directly they should still see a usefull error. I don't think this fix belongs in the build tooling so I'm going to close.  It probably does make sense as extra validation in gcloud.
