### ISSUE TITLE
If the gcloud is on the path, the plugin should use that to find the SDK path

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/app-maven-plugin#118]
If the `gcloud` command is installed, but it is not in the "standard" `$HOME/google-cloud-sdk` path, then the plugin should be able to [use the `gcloud` command to get the Google Cloud SDK path](http://stackoverflow.com/a/40938611/101923).

```
$ gcloud --format='value(installation.sdk_root)' info
/Users/username/google-cloud-sdk
```

Example [the build failed for the initial PR to use this plugin in the App Engine standard hello world sample](https://travis-ci.org/GoogleCloudPlatform/appengine-try-java/builds/180499041) with the error:

```
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.0.0:run (default-cli) on project appengine-try-java: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.0.0:run failed: Google Cloud SDK path was not provided and could not be found in any known install locations. -> [Help 1]
```

I believe this is because Travis runs on Google Cloud and the `gcloud` command is already installed, but in a "non-standard" location. I was able to work around this by running

```
mvn appengine:run \
    -DcloudSdkPath="$(gcloud --format='value(installation.sdk_root)' info)"
```

I shouldn't have to do this since the `gcloud` command is on the PATH already, so the plugin should be able to call this itself.

**Comment by loosebazooka** [comment]
should be fixed in next release.
