### ISSUE TITLE
Found an unexpected 'openapi.yaml' file in the App Engine directory

### ISSUE THREAD

**Issue by Eng-Fouad** [GoogleCloudPlatform/app-maven-plugin#119]
The plugin doesn't support openapi.yaml yet. It's expecting swagger.yaml instead.

**Comment by patflynn** [comment]
https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/258

As soon as that's merged we'll update this plugin to support openapi.yaml.

**Comment by loosebazooka** [comment]
openapi.yaml isn't deployed by the standard deployment path, so it doesn't actually make sense to include it in your app deployment flow.

@paflynn shouldn't users just be deploying these items on their own. using `gcloud beta service-management deploy` ?
