### ISSUE TITLE
genRepoInfoFile goal missing

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/app-maven-plugin#123]
This is mentioned in the README

[ERROR] Could not find goal 'genRepoInfoFile' in plugin com.google.cloud.tools:appengine-maven-plugin:1.0.0 among available goals deploy, help, run, stage, start, stop -> [Help 1] [ERROR]

**Comment by elharo** [comment]
problem appears to be a disconnect between the version in the readme (1.0.0) and the version where genRepoInfoFile appears (1.1.0-beta)

**Comment by patflynn** [comment]
@joaoandremartins any idea what happened here? I believe you removed this a while back and see the revert CL still pending: https://github.com/GoogleCloudPlatform/app-maven-plugin/pull/110

**Comment by joaoandremartins** [comment]
I think I accidentally reverted that README change when I released the new version 1.1.0-beta.

https://github.com/GoogleCloudPlatform/app-maven-plugin/commit/0de8f21ec863eedaa911044592848bb0a2c2789b

If everyone agrees, then we should release 1.1.0 and up the version in the README template.

@meltsufin WDYT?

**Comment by meltsufin** [comment]
I'm OK with moving 1.1.0-beta to 1.1.0, but I'll defer to @patflynn for the decision because I know there were concerns around requiring to configure an execution of the `genRepoInfoFile`.

**Comment by patflynn** [comment]
@meltsufin @loosebazooka Let's release 1.1.0 with genRepoInfoFile.

**Comment by loosebazooka** [comment]
undocumented? or with documentation?

**Comment by patflynn** [comment]
w/ docs.  Let's launch these commands as part of the AE plugin.

**Comment by joaoandremartins** [comment]
Anyone on top of this?

**Comment by loosebazooka** [comment]
It'll go out with the next release

**Comment by joaoandremartins** [comment]
I meant if anyone was on top of releasing the next version. :)
I'll assume you are ^^

**Comment by loosebazooka** [comment]
yup

**Comment by patflynn** [comment]
@loosebazooka this should be closed right?
