### ISSUE TITLE
double spaced dev appserver output in Windows

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-maven-plugin#127]
steps to reproduce:

On windows 10:
1) checkout https://github.com/patflynn/appengine-potpourri
2) cd endpoints-frontend
3) mvn appengine:run

observe:
`
warning: [options] bootstrap class path not set in conjunction with -source 1.7
:endpoints-frontend:compileJava
:endpoints-frontend:processResources UP-TO-DATE
:endpoints-frontend:classes
:endpoints-frontend:war
:endpoints-frontend:explodeWar
:endpoints-frontend:assemble
:endpoints-frontend:appengineRun
INFO     2017-01-23 16:09:04,924 devappserver2.py:764] Skipping SDK update check.
WARNING  2017-01-23 16:09:05,263 simple_search_stub.py:1146] Could not read search indexes from c:\users\patrick\appdata\local\temp\appengine.None\search_indexes
INFO     2017-01-23 16:09:05,269 api_server.py:268] Starting API server at: http://localhost:65470
INFO     2017-01-23 16:09:05,273 dispatcher.py:199] Starting module "default" running at: http://localhost:8080
INFO     2017-01-23 16:09:05,278 admin_server.py:116] Starting admin server at: http://localhost:8000
INFO     2017-01-23 16:09:05,795 module.py:415] [default] Detected file changes:
  WEB-INF\appengine-generated
Jan 23, 2017 9:09:06 PM com.google.appengine.tools.development.AbstractContainerService configure

WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)

Jan 23, 2017 9:09:06 PM com.google.apphosting.utils.jetty.JettyLogger info

INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger

Jan 23, 2017 9:09:07 PM com.google.apphosting.utils.jetty.JettyLogger info

INFO: jetty-6.1.x

Jan 23, 2017 9:09:08 PM com.google.apphosting.utils.jetty.JettyLogger info

INFO: Started SelectChannelConnector@localhost:65471

Jan 23, 2017 9:09:08 PM com.google.appengine.tools.development.AbstractModule startup

INFO: Module instance default is running at http://localhost:65471/

Jan 23, 2017 9:09:08 PM com.google.appengine.tools.development.AbstractModule startup

INFO: The admin console is running at http://localhost:65471/_ah/admin

Jan 23, 2017 9:09:08 PM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart

INFO: Dev App Server is now running

Jan 23, 2017 9:09:11 PM com.google.appengine.tools.development.LocalResourceFileServlet doGet

WARNING: No file found for: /_ah/warmup

INFO     2017-01-23 16:09:11,812 module.py:806] default: "GET /_ah/warmup HTTP/1.1" 404 83
The daemon will cancel the build.
`

**Comment by JoeWang1127** [comment]
close as not planned
