### ISSUE TITLE
don't package yaml service config files into the exploded webapp directory

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-maven-plugin#128]
During staging we copy the generated yaml files derived from cron.xml, dos.xml, etc into both:

`
$build.output/appengine-staging/..
`
and
`
$build.output/apengine-staging/WEB-INF/appengine-generated/.
`

copying under WEB-INF is OK because that's what the old code used to do, although I think we should consider deprecating that behavior, but we should definitely not copy these files into the base path as there is a chance the user could accidentally configure their web.xml to serve these files.

**Comment by loosebazooka** [comment]
This happens in the staging library itself... @ludoch what do you think about changing back to only moving app.yaml down in to the root directory and leaving everything else in appengine-generated. Also @patflynn should we just do this here for now? and push it upstream when we can?

**Comment by loosebazooka** [comment]
This change goes out with the gcloud appengine extensions, out tooling doesn't need to change.
