### ISSUE TITLE
Add parameter "requireIndexes" to "appengine:run" to support "--require_indexes True/False"

### ISSUE THREAD

**Issue by tekkamanendless** [GoogleCloudPlatform/app-maven-plugin#133]
I like to run my development server as close to true App Engine as I can, and that means having it fail when an index is not present.  "dev_appserver.py" has a parameter called "--require_indexes" that toggles this behavior on (the default is off), but there's currently no Maven parameter to do this.

Given how most of the other Maven parameters directly match up with the command-line ones, I recommend a "requireIndexes" parameter that accepts "true" or "false".

**Comment by patflynn** [comment]
Makes sense.

@loosebazooka can you check if there are other flags we're missing?
