### ISSUE TITLE
appengine:run does not show any indexes for Java standard instances, even though "datastore-index.xml" is present

### ISSUE THREAD

**Issue by tekkamanendless** [GoogleCloudPlatform/app-maven-plugin#134]
When I run the development server via "mvn appengine:run", I do not see any indexes in the administrative console.  I have set up "datastore-index.xml" appropriately (under the "WEB-INF" directory).  Prior to migrating everything to Maven this weekend, these indexes used to show up just fine under the App Engine SDK development server.

The same goes for cron jobs, even though "cron.xml" is set up appropriately.

For fun, I tried to copy the "index.yaml" and "cron.yaml" files from my "appengine-staging" directory into my current target directory, but that just made the development server fail with an error about not being allowed to use both YAML and XML configuration files in one project.

**Comment by patflynn** [comment]
this may be a devappserver2 gap.  @loosebazooka can you verify this? We may need to add this to the deprecation hotlist. b/hotlists/401188

**Comment by akerekes** [comment]
Workaround is available as of 1.3.0-rc1 which by default uses devappserver1 for local runs which handles `datastore-index.xml` correctly.

**Comment by jfinci1** [comment]
Hi- i believe I am encountering this as well currently.  Is the suggested workaround still the best option?

**Comment by chanseokoh** [comment]
We switch to devappserver1 a long time ago. Shouldn't be an issue.

@jfinci1 I see you opened #304, so I'll close this.
