### ISSUE TITLE
GCS / Blobstore emulator not compatible

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/app-maven-plugin#142]
https://github.com/GoogleCloudPlatform/appengine-gcs-client
https://cloud.google.com/appengine/docs/standard/java/googlecloudstorageclient/setting-up-cloud-storage

This maven plugin is not compatible with the gcloud SDK based maven plugin.

**Comment by loosebazooka** [comment]
Can you elaborate?

**Comment by lesv** [comment]
Yes - DevAppServer2 thing.  b/34039598

**Comment by akerekes** [comment]
Duplicate of #106
