### ISSUE TITLE
"deploy" Goal does not cover queues

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/app-maven-plugin#143]
Hi,
I have a Java Maven-based project with the following file system
![image](https://cloud.githubusercontent.com/assets/12278553/23452381/6620e46c-fe64-11e6-97d8-9b4803796904.png)

I noticed that the goal `com.google.cloud.tools:appengine-maven-plugin:deploy` only deploy the application, the `queue.xml` is not handled. I discovered this because I created a new queue but during the deploy procedure the queue has been not created online (and I got an error for queue not defined)

Is there an additional configuration required in order to deploy all the files? (application, queues, crons, ...)

The strange thing is that inside the staging directory i can see `appengine-staging/queue.yaml`, in addition to the original file `appengine-staging/WEB-INF/queue.xml`

At the end in order to deploy the updated queue file I used the `com.google.appengine:appengine-maven-plugin:update_queues` goal with the previous App Engine Maven plugin

**Comment by patflynn** [comment]
@NicolaSpreafico Sorry for the inconvenience. We will be introducing similar goals for this Maven plugin soon.

In the mean time you can add the appengine-staging/queue.yaml to your list of deployables in your plugin config. (you'll also need to add the generated app.yaml if you want to deploy the application with it).

**Comment by NicolaSpreafico** [comment]
@patflynn Thank you, I understand from [the documentation](https://cloud.google.com/appengine/docs/standard/java/tools/maven-reference#appenginedeploy) that I need to use the `deployables` parameter.

Reading other issue like:
* https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/89#issuecomment-248937273
* https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/90
* https://github.com/GoogleCloudPlatform/nodejs-getting-started/issues/56
I now created a configuration like this (I configured `app.yaml` as well as you suggested)

```
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>appengine-maven-plugin</artifactId>
    <version>${appengine.maven.plugin.version}</version>
    <configuration>
        <deploy.project>${app.id}</deploy.project>
        <deploy.version>${app.version}</deploy.version>
        <deploy.promote>False</deploy.promote>
        <stage.enableJarClasses>true</stage.enableJarClasses>
        <stage.stagingDirectory>${java.io.tmpdir}/appengine-staging</stage.stagingDirectory>
        <deployables>
            <param>${java.io.tmpdir}/appengine-staging/app.yaml</param>
            <param>${java.io.tmpdir}/appengine-staging/cron.yaml</param>
            <param>${java.io.tmpdir}/appengine-staging/queue.yaml</param>
            <param>${java.io.tmpdir}/appengine-staging/index.yaml</param>
        </deployables>
    </configuration>
</plugin>
```
Please note that the `stagingDirectory` parameter was already there, I configured the deployables param to follow that configuration.

I like very much the possibility of deploying ONLY the application and not the related files (cron, queue, ...) which with the previous deploy procedure was not possibile. You could the deploy only the queue/cron but not only the app. I also tried, as an example, to remove the `app.yaml` from the deploy and it works as well.

```
[INFO] GCLOUD: You are about to update the following configurations:
[INFO] GCLOUD: Updating config [cron]...
[INFO] GCLOUD: done.
[INFO] GCLOUD: Updating config [queue]...
[INFO] GCLOUD: done.
[INFO] GCLOUD: Updating config [index]...
[INFO] GCLOUD: done.
[INFO] GCLOUD: 
[INFO] GCLOUD: Cron jobs have been updated.
[INFO] GCLOUD: 
[INFO] GCLOUD: Task queues have been updated.
```

Now that I successfully configured the Maven plugin I can choose file per file to deploy.
I can comment and uncomment the param lines in order to deploy only the proper files (which is not very comfortable but at least can be done).

**Comment by patflynn** [comment]
Thanks for the detailed comments. We'll try to design it so that we
maintain the ability to deploy only the app without the related files.

**Comment by boogie4eva** [comment]
This doesn't work for cloud endpoints projects

**Comment by patflynn** [comment]
@boogie4eva deploying indexes and the app doesn't work for endpoints projects?

**Comment by loosebazooka** [comment]
@boogie4eva do you mean it's not deploying your endpoints config?

**Comment by NicolaSpreafico** [comment]
@patflynn  @loosebazooka 
Basing on the [SO question](http://stackoverflow.com/questions/42608985/queue-yaml-not-deployed-when-i-use-mvn-appenginedeploy?) that brought @boogie4eva here, I understand that the problem was not specific to the Cloud Endpoints per se but to the 1.2.0 plugin version that I reported [here](https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/144)

**Comment by patflynn** [comment]
@loosebazooka @meltsufin this issue seems pretty critical. What do you guys thinking about doing a fix release for gradle/maven ASAP?

**Comment by loosebazooka** [comment]
maven fix is going out the door, this doesn't affect gradle.

**Comment by depsypher** [comment]
Was this fixed? We're using v1.2.1 and deploy doesn't seem to update queues.xml for us.

**Comment by loosebazooka** [comment]
@depsypher the issue in this bug is fixed. If nothing in this issue works please open a new bug with your specific issue.

**Comment by boogie4eva** [comment]
It works with 1.0 .0 is it fixed for the latest release ?.
