### ISSUE TITLE
Ignore errors on genRepoInfoFile

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/app-maven-plugin#148]
If I run mvn package but a project isn't version controlled, packaging fails and I get the following from the plugin:

Mar 07, 2017 2:47:51 PM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: /Users/joaomartins/google-cloud-sdk/bin/gcloud beta debug source gen-repo-info-file --output-directory /Users/joaomartins/Downloads/demo/target/classes --source-directory /Users/joaomartins/Downloads/demo
[INFO] GCLOUD: ERROR: gcloud crashed (GenerateSourceContextError): Could not list remote URLs from source directory: /Users/joaomartins/Downloads/demo

We should probably allow a "ignoreErrors" flag so, if there are any errors during source context generation, the build lifecycle can still proceed.

**Comment by patflynn** [comment]
there is an ignoreErrors flag, although I thought it was defaulted to true.  I suppose as long as the user has to explicitly bind the command to an execution it could be OK as is.

one thing I'm noticing is that we're using the 'beta' subcommand, and I think the command has been GA'd.
