### ISSUE TITLE
appengine:run does not receive environment variables when using devappserver2

### ISSUE THREAD

**Issue by stickfigure** [GoogleCloudPlatform/app-maven-plugin#150]
It appears that environment variables from the shell do not make it to the dev appserver with the new maven plugin. Ie:
```
$ export GOOGLE_APPLICATION_CREDENTIALS=/path/to/file
$ mvn appengine:run
```
Running `System.getenv("GOOGLE_APPLICATION_CREDENTIALS")` in the app produces null. Using the old `mvn appengine:devserver`, this environment variable was visible in the app.

This is a rather serious problem because the `GOOGLE_APPLICATION_CREDENTIALS` environment variable is used by the gcloud java SDK to simulate default credentials with a private key. This is the only way to produce default credentials in the devserver that can sign GCS urls; the normal `gcloud auth application-default login` doesn't have the private key. It's painful to work around this - basically we have to code "if in dev mode then sign requests in a different way" into the app.

This problem also happens when running the dev server in IDEA; I presume it's the same issue?

**Comment by patflynn** [comment]
@stickfigure thanks for the report and detailed context.

@ludoch was this working with the old plugin simply because devappserver v1 isn't blocking out the local environment variables?

**Comment by akerekes** [comment]
@stickfigure can you test it with either 1.3.0-rc1 or -rc2 to see if it works with devappserver1?

**Comment by stickfigure** [comment]
It works using 1.3.0-rc1 via `mvn appengine:run`, thanks!

However, when starting appengine via the IDEA plugin ("Google App Engine Standard Local Server"), environment variables still aren't making it to the server. Is that a different team this needs to be reported to?

**Comment by akerekes** [comment]
Which version of the IDEA plugin do you use? By looking at the repo and the releases the latest version should work as well. @etanshaul @patflynn can you confirm this?

**Comment by stickfigure** [comment]
Version 17.2.4_2017. Check update doesn't seem to find anything more recent.

Here's what my run config looks like: http://take.ms/2PFie

When I print `System.getenv()` at startup, GOOGLE_APPLICATION_CREDENTIALS is not present.

Probably unrelated, but it is odd that the -D flag is present in this list with an empty variable name. It appears to be drawing that value from VM options on the Server tab.

**Comment by patflynn** [comment]
To get this to work in IJ for now you'll need to set the environment
variable some other way (OS dependent).  You're right that we're not
passing the variables set in the run config ui.

The reason for the weirdness is that the devappserver2 and devappserver1
behave differently WRT environment variables.  Devappserver2 will configure
them from your appengine-web.xml and ignore anything set locally, to better
mimick how the real app engine environment works.  Devappserver1 couldn't
do this (as there's no way to set environment variables from within the
JVM) so they expect the user to configure the variables themselves before
the run and produce an error if those values don't match what's in the
appengine-web.xml.

DevAppserver2 is the 'correct' behavior, but with the new client libraries
auth magic going on people are having problems configuring their
environment for the credentials to work.  Devappserver2 introduce an
 'env_var' flag to deal with this, but now that we're back on devappserver1
you can simply set the environment manually yourself and it will be picked
up.

**Comment by stickfigure** [comment]
When you say "set the environment manually", do you mean as a systemwide environment variable? This is somewhat problematic since we work with multiple projects and each project has its own security credentials. This really should be part of the run config.

That said, this is significantly better than before! We can probably live with it for a while. Thanks.

**Comment by patflynn** [comment]
Yeah that's what I meant.  I agree that this is broken and we need to come
up with a better model.
