### ISSUE TITLE
v1.2.1 conflicts with the old appengine-maven-plugin

### ISSUE THREAD

**Issue by stickfigure** [GoogleCloudPlatform/app-maven-plugin#152]
Through v1.2.0, the new plugin could coexist with the old plugin. For example, I have this in my pom.xml:

```xml
<plugin>
	<groupId>com.google.appengine</groupId>
	<artifactId>appengine-maven-plugin</artifactId>
	<version>${gae.version}</version>
</plugin>
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>appengine-maven-plugin</artifactId>
	<version>1.2.0</version>
</plugin>
```

The old plugin can be run with `mvn appengine:devserver` and the new plugin can be run with `mvn com.google.cloud.tools:appengine-maven-plugin:run`. They coexist fine. However, upgrading the new plugin to 1.2.1 breaks behavior in the old plugin.

With version 1.2.0 of the com.google.cloud.tools plugin installed in the POM, running the old com.google.appengine:appengine-maven-plugin:devserver executes this (correct) command line:

```
[INFO] Running /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java -XstartOnFirstThread -D--enable_all_permissions=true -Xbootclasspath/p:/Users/jeff/.m2/repository/com/google/appengine/appengine-java-sdk/1.9.50/appengine-java-sdk/appengine-java-sdk-1.9.50/lib/override/appengine-dev-jdk-overrides.jar -Dappengine.fullscan.seconds=5 -Duse_jetty9_runtime=true -classpath /Users/jeff/.m2/repository/com/google/appengine/appengine-java-sdk/1.9.50/appengine-java-sdk/appengine-java-sdk-1.9.50/lib/appengine-tools-api.jar com.google.appengine.tools.development.DevAppServerMain --allow_remote_shutdown --no_java_agent /Users/jeff/workspace/orbitkit/houston/target/orbitkit-houston-1.0-SNAPSHOT
```

Upgrading the com.google.cloud.tools plugin to v1.2.1 causes the _old_ plugin's appengine:devserver to execute this commandline:

```
[INFO] Running /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java -XstartOnFirstThread -D--enable_all_permissions=true -Xbootclasspath/p:/Users/jeff/.m2/repository/com/google/appengine/appengine-java-sdk/1.2.1/appengine-java-sdk/appengine-java-sdk-1.2.1/lib/override/appengine-dev-jdk-overrides.jar -Dappengine.fullscan.seconds=5 -Duse_jetty9_runtime=true -classpath /Users/jeff/.m2/repository/com/google/appengine/appengine-java-sdk/1.2.1/appengine-java-sdk/appengine-java-sdk-1.2.1/lib/appengine-tools-api.jar com.google.appengine.tools.development.DevAppServerMain --allow_remote_shutdown --no_java_agent /Users/jeff/workspace/orbitkit/houston/target/orbitkit-houston-1.0-SNAPSHOT
```

Notice that the appengine-java-sdk version has mysteriously changed from **1.9.50** to **1.2.1**, which is clearly not right.

**Comment by loosebazooka** [comment]
I can recreate this, i'll take a deeper look, this is is so weird.

**Comment by loosebazooka** [comment]
For some reason changing the version affects the order in which the plugins are discovered when trying to download the appengine SDK, see here for old plugin downloading the code : https://github.com/GoogleCloudPlatform/appengine-maven-plugin/blob/master/src/main/java/com/google/appengine/SdkResolver.java#L53 Since it isn't checking groupId, the value is being extracted from the new plugin's artifactId.

I would maybe file this bug against https://github.com/GoogleCloudPlatform/appengine-maven-plugin, but we want people to be using this new plugin because it uses newer tooling under hood. I'd like to understand the usecase for having both plugins in your build file though? What do we need to improve to get you to use only the `com.google.cloud.tools` plugin?

**Comment by stickfigure** [comment]
I'm in Ludo's test group and I sometimes hit issues the new plugin. Having one right now that's a showstopper; crafting an email to that list right now. Not sure if I should file the issue here but seems safer on the list?

**Comment by loosebazooka** [comment]
The list is fine.

**Comment by stickfigure** [comment]
With the 1.9.51 com.google.appengine plugin this no longer appears to be an issue. Closing.
