### ISSUE TITLE
"deploy" Goal does not cover queues

### ISSUE THREAD

**Issue by depsypher** [GoogleCloudPlatform/app-maven-plugin#153]
As described in issue #143 the deploy goal doesn't seem to update the queues out of the box, and specifying it in the config generates an error for me:

```
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.2.1:deploy (default-cli) on project orbitkit-houston: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.2.1:deploy failed: Deployable /tmp/appengine-staging/queue.yaml does not exist. -> [Help 1]
```

My config:
```
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>appengine-maven-plugin</artifactId>
	<version>1.2.1</version>
	<configuration>
		<deploy.promote>true</deploy.promote>
		<deploy.stopPreviousVersion>true</deploy.stopPreviousVersion>
		<stage.stagingDirectory>${java.io.tmpdir}/appengine-staging</stage.stagingDirectory>
		<deployables>
			<param>${java.io.tmpdir}/appengine-staging/app.yaml</param>
			<param>${java.io.tmpdir}/appengine-staging/queue.yaml</param>
		</deployables>
	</configuration>
</plugin>
```

**Comment by depsypher** [comment]
I'm not sure it matters, since it's a devserver thing, but this is the same project affected by Issue #152.

It means we won't be able to upgrade from v1.2.0 until that bug is fixed as well, but in any case I get that "queue.yaml does not exist" error on deploy under both v1.2.0 and v1.2.1.

**Comment by meltsufin** [comment]
@depsypher Do you actually have the file in `/tmp/appengine-staging/queue.yaml` with the correct permissions?

**Comment by loosebazooka** [comment]
I believe the newest version of staging directory creation doesn't copy configuration yamls (except app.yaml which is required at root for gcloud deployments) down to root.

If you inspect the directory, I believe the files should be in :
```
/appengine-staging/WEB-INF/appengine-generated/queue.yaml
```

**Comment by depsypher** [comment]
The plugin doesn't seem to be creating the `queue.yaml` in my case. It does create it under v1.2.0, but we hit a different bug in that case (`ERROR: Directories are not supported`). Here's output directly from circleci using v1.2.1:
```
INFO: submitting command: /usr/lib/jvm/jdk1.8.0/jre/bin/java -cp /opt/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com.google.appengine.tools.admin.AppCfg --disable_update_check stage /home/ubuntu/houston/target/orbitkit-houston-1.0-SNAPSHOT /tmp/appengine-staging
[INFO] GCLOUD: Reading application configuration data...
[INFO] GCLOUD: 
[INFO] GCLOUD: 
[INFO] GCLOUD: Beginning interaction for module default...
[INFO] GCLOUD: 0% Scanning for jsp files.
[INFO] GCLOUD: 0% Generated git repository information file.
[INFO] GCLOUD: Success.
[INFO] GCLOUD: Temporary staging for module default directory left in /tmp/appengine-staging
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.801 s
[INFO] Finished at: 2017-03-20T16:31:00+00:00
[INFO] Final Memory: 33M/1006M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.2.1:deploy (default-cli) on project orbitkit-houston: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.2.1:deploy failed: Deployable /tmp/appengine-staging/queue.yaml does not exist. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
ubuntu@box899:~/houston$ ls -al  /tmp/appengine-staging
total 20
drwxrwxr-x 1 ubuntu ubuntu  144 Mar 20 16:31 .
drwxrwxrwt 1 root   root    632 Mar 20 16:30 ..
-rw-rw-r-- 1 ubuntu ubuntu 2686 Mar 20 16:30 app.html
-rw-rw-r-- 1 ubuntu ubuntu  347 Mar 20 16:31 app.yaml
drwxrwxr-x 1 ubuntu ubuntu   44 Mar 20 16:30 dist
-rw-rw-r-- 1 ubuntu ubuntu 1406 Mar 20 16:30 favicon.ico
drwxrwxr-x 1 ubuntu ubuntu   20 Mar 20 16:30 img
-rw-rw-r-- 1 ubuntu ubuntu 1310 Mar 20 16:30 nixon2.html
-rw-rw-r-- 1 ubuntu ubuntu 1587 Mar 20 16:30 nixon.html
drwxrwxr-x 1 ubuntu ubuntu   94 Mar 20 16:30 __static__
drwxrwxr-x 1 ubuntu ubuntu  176 Mar 20 16:31 WEB-INF
```

**Comment by loosebazooka** [comment]
v1.2.0 had a bug with `directories not supported` that is now fixed.

However, please see the comment above about the location of queue.yaml

**Comment by depsypher** [comment]
Please look at my output posted above. It shows that I'm using 1.2.1 and that queue.yaml doesn't exist in /tmp/appengine-staging.

**Comment by loosebazooka** [comment]
@depsypher `appengine-staging/WEB-INF/appengine-generated/queue.yaml`, it is not copied to the root directory anymore

**Comment by depsypher** [comment]
Am I expected to manually create queue.yaml mirroring the info I've already defined in queue..xml and then manually copy it into that directory? Surely that's the job of the plugin, no?

**Comment by loosebazooka** [comment]
Is there no queue.yaml in `/tmp/appengine-staging/WEB-INF/appengine-generated/queue.yaml` ?

The plugin will soon have individual goals for each .yaml, but we disabled copying to root because it doesn't make sense to have them sit next to the application context (app.yaml) during deployment.

**Comment by depsypher** [comment]
For the sake of argument let's say it exists there (reproducing this is each time takes a bit of work I'd rather avoid).

The plugin is still reporting an error that fails my build. That error claims it is looking for that file in the root and can't find it there. Is it possible that code was changed to generate the file in a new location, but a reference to the old location was not updated?

**Comment by loosebazooka** [comment]
The plugin doesn't set any value by default except app.yaml. It appears like through your configuration you're setting it, have you removed that line? From the first comment on this thread :

```
			<param>${java.io.tmpdir}/appengine-staging/queue.yaml</param>
```

**Comment by depsypher** [comment]
Nope, I haven't removed anything. I'm running this with the config set exactly as shown in the first comment :)

**Comment by loosebazooka** [comment]
So? Now it works with that line removed/changed?

**Comment by depsypher** [comment]
Sorry I'm confused now. My impression was that you needed to specify both the app.yaml and the queue.yaml in the config so that's what I've been doing. If that's not correct, could you post your edits to the config in the first comment you'd like me to try?

**Comment by depsypher** [comment]
I just want to deploy my app and have the queues update. Any help getting that working would be greatly appreciated. Doesn't matter if it's a workaround, or just waiting for a bug fix. Happy to help diagnose further if you are having trouble reproducing.

**Comment by loosebazooka** [comment]
Okay, so what's happening in the first comment is a non-standard configuration. I've changed it up a little to be more standard.

```xml
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>appengine-maven-plugin</artifactId>
	<version>1.2.1</version>
	<configuration>
                <!-- promote is set to true by default, you don't need this -->
		<!-- deploy.promote>true</deploy.promote -->

                <!-- stopPreviousVersion does not apply for standard appengine application -->
		<!-- deploy.stopPreviousVersion>true</deploy.stopPreviousVersion -->

                <!-- remove this customized staging directory, just use the standard maven build dir -->
		<!-- stage.stagingDirectory>${java.io.tmpdir}/appengine-staging</stage.stagingDirectory -->
		<deployables>
                        <!-- by default, ${project.build.directory}/appengine-staging is the output directory -->
                        <!-- app.yaml in root of staging (default configuration) -->
			<param>${project.build.directory}/appengine-staging/app.yaml</param>
                        <!-- queue.yaml is in the generated dir of staging -->
			<param>${project.build.directory}/appengine-staging/WEB-INF/appengine-generated/queue.yaml</param>
		</deployables>
	</configuration>
</plugin>
```

**Comment by chanseokoh** [comment]
Can you update the queue.xml location you are setting in pom.xml to the location @loosebazooka suggested (i.e., under WEB-INF/) and see if it works?

**Comment by depsypher** [comment]
Excellent, thanks, that gets me further. Sorry for the disconnect on the path change, my bad for missing that I needed to update it in deployables.

Now with that config I get this new error, which does not happen when the `deployables` section is removed:
```
[INFO] GCLOUD:  - voodoodyne0/queue  (from [/home/ubuntu/houston/target/appengine-staging/WEB-INF/appengine-generated/queue.yaml])
[INFO] GCLOUD: Beginning deployment of service [default]...
[INFO] GCLOUD: File upload done.
[INFO] GCLOUD: Updating service [default]...
[INFO] GCLOUD: ................................done.
[INFO] GCLOUD: Deployed service [default] to [https://voodoodyne0.appspot.com]
[INFO] GCLOUD: Updating config [queue]...
[INFO] GCLOUD: failed.
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Server responded with code [403]:
[INFO] GCLOUD:   Forbidden Unexpected HTTP status 403.
[INFO] GCLOUD:   You do not have permission to modify this app (app_id=u's~voodoodyne0').
```

I've checked the IAM account doing the deploy and it has AppEngine Deployer privs (and Service Admin).

Should I file a new bug for this?

**Comment by loosebazooka** [comment]
@znewman01 ? Do you know what this error means in this context?

**Comment by znewman01** [comment]
I think that (counterintuitively) the Deployer role is *not* sufficient to deploy everything in your app (for instance, queues). I can try to loop someone in who would know better.

**Comment by depsypher** [comment]
Thanks for the help guys.

I just tried enabling AppEngine Admin on that IAM account as well and still get the same failing result. Not sure what other permission might be required.

Hopefully it's a simple setting I'm missing somewhere?

**Comment by znewman01** [comment]
I think someone who knows the details here will get back to me soon, so we can answer for certain.

**Comment by akerekes** [comment]
@depsypher Were you able to resolve this issue?

**Comment by depsypher** [comment]
Unfortunately not. We worked around it for now by using the old maven plugin to push queue changes, but we'd like the new plugin to be able to handle this use case.

**Comment by loosebazooka** [comment]
@znewman01 any update on the loop-in?

**Comment by znewman01** [comment]
@JustinBeckwith

**Comment by JustinBeckwith** [comment]
The "App Engine Deployer" role does not have IAM permissions to deploy queue.yaml.  For that, you either need to be a Project Editor, or you need to be enrolled in our Cloud Tasks alpha which includes a Cloud Task Admin role.  

Let me know if you want to learn more about the alpha, and sorry for the trouble!

**Comment by depsypher** [comment]
Awesome, can confirm that queues get updated on deploy once the IAM account has the Editor role assigned. Thanks guys 👍
