### ISSUE TITLE
Add deploy mojos for config files

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/app-maven-plugin#155]
```
appengine:deployCron
appengine:deployDispatch
appengine:deployDos
appengine:deployIndex
appengine:deployQueue
```

configuration through :
```
<appEngineDirectory/> // for configuration file locations
<project/> // to specify gcloud project
```

**Comment by loosebazooka** [comment]
Also, the default for appEngineDirectory should be 
${project.build.directory}/appengine-staging/WEB-INF/appengine-generated 
for standard projects

which might collide with the parameter being set for flexible staging.

**Comment by patflynn** [comment]
I kinda liked the appengineProjectConfigDirectory name.  the problem with appEngineDirectory is that as a standard user I would probably expect that to be where I have my appengine-web.xml.  Which always would have to be under web-inf so it's a bit confusing. 

Also I'm not sure you'd ever want the config directory to be in the target tree.  Can users of the old tools configure where xml files are converted into yamls?    I think if the user has all their configs in xmls then they should be under WEB-INF in the src tree and that config directory is meaningless.  

We also need to think about how the devappserverV1 configures its emulators, I don't think it works if the configs aren't under the target../WEB-INF//. directory

**Comment by loosebazooka** [comment]
I'm a little confused by what you mean, but auto generated yamls are in the target directory. Perhaps there's a problem in how we are exposing our deployment and what a user might expect. But we can change naming and convention still.
