### ISSUE TITLE
Maven plugin doesn't seem to respect appYamls parameters.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-maven-plugin#159]
If you take a look at the endpoints-frontend in this repo:
https://github.com/patflynn/appengine-potpourri/tree/cloud-sdk-refactor

you'll see local run to configure multi-modules:
```
                    <appYamls>
                        <appYaml>${project.build.directory}/appengine-staging/app.yaml</appYaml>
                        <appYaml>
                            ${project.parent.basedir}/jdo-backend/target/appengine-staging/app.yaml
                        </appYaml>
                    </appYamls>
```

When I use `mvn appengine:run` the command executed is:
`/usr/local/google/home/paflynn/google-cloud-sdk/bin/dev_appserver.py /usr/local/google/home/paflynn/work/appengine-potpourri/endpoints-frontend/target/endpoints-frontend-1.0`

and only the endpoint-frontend appears to be running. 

I would expect configuring the parameter the way I have that both staged app.yaml paths would be passed to gcloud and both services would be running locally after mvn appengine:run.

**Comment by patflynn** [comment]
FYI @loosebazooka

**Comment by akerekes** [comment]
@patflynn I cannot reproduce this. I see the following command executed:
```
INFO: submitting command: /usr/local/google/home/akerekes/google-cloud-sdk/bin/dev_appserver.py /usr/local/google/home/akerekes/work/checkout/appengine-potpourri/endpoints-frontend/target/appengine-staging/app.yaml /usr/local/google/home/akerekes/work/checkout/appengine-potpourri/jdo-backend/target/appengine-staging/app.yaml --jvm_flag=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n --jvm_flag=-Dappengine.user.timezone=UTC
```

However I get an error: 
```
[INFO] GCLOUD: Traceback (most recent call last):
[INFO] GCLOUD:   File "/usr/local/google/home/akerekes/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 101, in <module>
[INFO] GCLOUD:     _run_file(__file__, globals())
[INFO] GCLOUD:   File "/usr/local/google/home/akerekes/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 97, in _run_file
[INFO] GCLOUD:     execfile(_PATHS.script_file(script_name), globals_)
[INFO] GCLOUD:   File "/usr/local/google/home/akerekes/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1041, in <module>
[INFO] GCLOUD:     main()
[INFO] GCLOUD:   File "/usr/local/google/home/akerekes/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1037, in main
[INFO] GCLOUD:     dev_server.stop()
[INFO] GCLOUD:   File "/usr/local/google/home/akerekes/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 845, in stop
[INFO] GCLOUD:     metrics.GetMetricsLogger().Stop()
[INFO] GCLOUD:   File "/usr/local/google/home/akerekes/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/metrics.py", line 117, in Stop
[INFO] GCLOUD:     total_run_time = int((Now() - self._start_time).total_seconds())
[INFO] GCLOUD: TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
```
Which looks similar to https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/161

**Comment by patflynn** [comment]
Yeah, that's a bug with the latest release of devappserver I think.

**Comment by akerekes** [comment]
So the error I get is `GCLOUD: IOError: [Errno 2] No such file or directory: '/usr/local/google/home/akerekes/work/checkout/appengine-potpourri/endpoints-frontend/target/appengine-staging/app.yaml'`
Which is correct, because there's no `appengine-staging` directory under `target`.

**Comment by loosebazooka** [comment]
For appengine java we shouldn't be running off the staged directory though. We need to run off the exploded app to ensure appengine-runtime dependencies are still available.

**Comment by akerekes** [comment]
So you mean the `appYamls` config is incorrect?

**Comment by loosebazooka** [comment]
Well the naming is certainly off, but the default value is the exploded-war directory, not the staged-app directory.

**Comment by akerekes** [comment]
What I meant is that in the above example project provided by @patflynn , the pom.xml has the following config:
```
                    <appYamls>
                        <appYaml>${project.build.directory}/appengine-staging/app.yaml</appYaml>
                        <appYaml>
                            ${project.parent.basedir}/jdo-backend/target/appengine-staging/app.yaml
                        </appYaml>
                    </appYamls>
```
which is incorrect, it shouldn't use the `appengine-staging` directory.
