### ISSUE TITLE
Document how I would configure my pom.xml to deploy all configs at the same time.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-maven-plugin#181]

**Comment by NicolaSpreafico** [comment]
[This is the configuration](https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/177#issuecomment-295747327) I'm using with plugin version 1.2.1.
Hope this helps

**Comment by patflynn** [comment]
Thanks @NicolaSpreafico.  I should have specified this bug is for 1.3.0 which changes things up a bit.

**Comment by patflynn** [comment]
Although your configuration is still good.
