### ISSUE TITLE
Bad version on Maven Central ?

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/app-maven-plugin#186]
http://mvnrepository.com/artifact/com.google.cloud.tools/appengine-maven-plugin

shows a 99.99.99 version : is this an intended release ?

http://mvnrepository.com/artifact/com.google.cloud.tools/appengine-maven-plugin/99.99.99

@lesv

**Comment by loosebazooka** [comment]
Correct. That was a misdeployment of a test on our side. The correct latest
version is 1.3.1, unfortunately we were only able to remove the artifact
but not the indexed repository. It should be removed during their next
reindexing during maintenance.
