### ISSUE TITLE
Improve error - "The Google Cloud SDK could not be found in the customary locations and no path was provided" - please

### ISSUE THREAD

**Issue by paul-hammant** [GoogleCloudPlatform/app-maven-plugin#190]
1. Customary locations could be detailed.
2. A URL could be included .. that talks of install.sh and source ~/.bash_profile etc.

Thanks.

Xref from https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/416

**Comment by hemanthk92** [comment]
this will tell you you installation path to google cloud sdk,
$(gcloud --format='value(installation.sdk_root)' info)

i then provided it as a parameter when i deployed my app engine instance

mvn appengine:deploy     -DcloudSdkPath="$(gcloud --form
at='value(installation.sdk_root)' info)"

**Comment by loosebazooka** [comment]
We also search on the path which should be enough to find it if you haven't changed things much.

**Comment by loosebazooka** [comment]
Oh this bug is from March, closing for now. But if you have a non-default installation, just set the home dir.

**Comment by paul-hammant** [comment]
"The Google Cloud SDK could not be found in the customary locations and no path was provided" ....... could simply point to an error page online (via a URL it could also print to std-err). 

Never mind, people searching will find this issue now.

**Comment by loosebazooka** [comment]
We can update the error messaging.

**Comment by patflynn** [comment]
would using $(gcloud --format='value(installation.sdk_root)' be an
improvement?

**Comment by CrisRys** [comment]
thanks @hemanthk92  your comment solved my issue.  Where is cloudSdkPath documented?

**Comment by chanseokoh** [comment]
Please see https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/416#issuecomment-350181571.

**Comment by serv-inc** [comment]
In case you came here after searching for the gradle error message: add `appengine.tools.cloudSdkHome="/path/to/google-cloud-sdk"` to you `build.gradle`. See https://stackoverflow.com/questions/49307284/the-google-cloud-sdk-could-not-be-found-in-the-customary-locations-and-no-path/51029339#51029339
