### ISSUE TITLE
appengine:run artifacts left over...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/app-maven-plugin#192]
@ludoch FYI @loosebazooka @patflynn HELP?

When I run my samples locally, I see extra stuff left over in weird places.  It may be we just need to document things correctly, but I think something else might be going on since we moved back to DevAppServer1

So, running the [search](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/search) example it creates a WEB-INF/appengine-generated file in the root of my project.

```
➜  search git:(master) ✗ ls -l
total 12
-rw-r--r--   1 lesv  eng   607 May 15 22:23 README.md
drwxr-xr-x   3 lesv  eng   102 May 22 14:21 WEB-INF
-rw-r--r--   1 lesv  eng  2509 May 19 14:27 appengine-search-j8.iml
-rw-r--r--@  1 lesv  eng  2937 May 18 13:10 pom.xml
drwxr-xr-x   4 lesv  eng   136 May 15 22:23 src
drwxr-xr-x  13 lesv  eng   442 May 22 14:21 target
```
```
➜  search git:(master) ✗ ls -R WEB-INF
appengine-generated

WEB-INF/appengine-generated:
indexes

WEB-INF/appengine-generated/indexes:
dGVzdA

WEB-INF/appengine-generated/indexes/dGVzdA:
VXRpbHNUZXN0SW5kZXg..P         c2NoZW1hSW5kZXg..P             c2VhcmNoSW5kZXg..P             c2VhcmNoSW5kZXhGb3JEZWxldGU..P c2VhcmNoT3B0aW9uSW5kZXg..P     dGVzdEluZGV4..P

WEB-INF/appengine-generated/indexes/dGVzdA/VXRpbHNUZXN0SW5kZXg..P:
_0.cfs       segments.gen segments_2   write.lock

WEB-INF/appengine-generated/indexes/dGVzdA/c2NoZW1hSW5kZXg..P:
_0.cfs       segments.gen segments_2   write.lock

WEB-INF/appengine-generated/indexes/dGVzdA/c2VhcmNoSW5kZXg..P:
_0.cfs       segments.gen segments_2   write.lock

WEB-INF/appengine-generated/indexes/dGVzdA/c2VhcmNoSW5kZXhGb3JEZWxldGU..P:
_0.cfs       _0_1.del     segments.gen segments_3   write.lock

WEB-INF/appengine-generated/indexes/dGVzdA/c2VhcmNoT3B0aW9uSW5kZXg..P:
_0.cfs       segments.gen segments_2   write.lock

WEB-INF/appengine-generated/indexes/dGVzdA/dGVzdEluZGV4..P:
_0.cfs       segments.gen segments_2   write.lock
```

I guess I'd expect this to be in either `src/main/webapp/WEB-INF` or `target/appengine-search-j8-1.0-SNAPSHOT/webapp/WEB-INF`.

What do you think?

**Comment by loosebazooka** [comment]
that's strange, lemme check it out.

**Comment by loosebazooka** [comment]
oh maybe it has something to do with the working directory? @ludoch?

**Comment by ludoch** [comment]
Maybe? What is the default dir in this execution?

**Comment by lesv** [comment]
Where WEB-INF was created. (at least that's where I was), probably should change ??

**Comment by loosebazooka** [comment]
It's likely related to this : https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/411

However, datastore-indexes-auto is correctly put in the right place. Perhaps dev appserver shouldn't be using working directory to write that, especially in the multimodule case. It should write it relative to the path of the WEB-INF dir.

**Comment by chanseokoh** [comment]
I don't think https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/411 is related, because https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/411 was merged after the 0.3.3 was released, which is the latest version currently.

**Comment by loosebazooka** [comment]
@chanseokoh our last release of the plugin was off of 0.3.2

**Comment by chanseokoh** [comment]
@loosebazooka Thanks for the correction. So it confirms https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/411 is not related.

**Comment by loosebazooka** [comment]
Oh by "related" I mean, the information in that bug could be relevant. Perhaps that fix would help alleviate this problem.

**Comment by patflynn** [comment]
can we test this with the latest plugins core to see if it fixes it?

**Comment by loosebazooka** [comment]
So this happens whether or not we specify the working directory. Which I find pretty confusing.

**Comment by patflynn** [comment]
Also this is only happening for search indexes and not other auto-generated
files right? At least I've never seen this behavior before.

**Comment by loosebazooka** [comment]
looks like these artifacts are from tests in this project.
running
```
mvn appengine:run -DskipTests
```
doesn't produce them.

**Comment by loosebazooka** [comment]
output from the running app is correctly written to `target/appengine-search-...../WEB-INF/appengine-generated`

**Comment by chanseokoh** [comment]
Looks like the culprit was the tests in this particular project. Closing.
