### ISSUE TITLE
appengine-web.xml (GAE Std) ignoring <application> is a bad idea

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/app-maven-plugin#194]
I thought the agreement was that we would compare to the current project if they were equal we'd let it go, if they were different, we'd stop.

This is causing users pain.

@rdayal FYI
@ludoch FYI

**Comment by loosebazooka** [comment]
Pain? Are there specific bug reports/github issues? It'd be nice to see why people don't like this.

**Comment by lesv** [comment]
Are you on the slack channel?

**Comment by TadCordle** [comment]
Addressed this in #291
