### ISSUE TITLE
"mvn appengine:run" doesn't pick up project-id

### ISSUE THREAD

**Issue by neozwu** [GoogleCloudPlatform/app-maven-plugin#202]
Using the new appengine-maven-plugin (1.3.1), it is no longer needed to specify ApplicationId in appengine-web.xml.  However, when running local server, the system property "com.google.appengine.application.id" (on both appengine std j8 and std j7) has a value of "no_app_id". This is the property that [google-cloud-java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L314) relies on to retrieve "application id" (it seems there's no other system property or env var that reveals project id on local server). On std j7, we also use [reflection](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L383) to consult appengine sdk class to get project id, which, on local server, returns "no_app_id" too.

**Comment by chanseokoh** [comment]
I do remember people discussing this issue in the past, a long time ago.

I don't think this repo is the right place to find a workable solution. This will happen regardless of appengine-maven-plugin or a build system, whether it be Maven, Gradle, or Ant. Some people don't even use any build system. (For example, our Eclipse plugin creates App Engine projects with no build system.)

But more crucially, users are not required to have an application ID in `appengine-web.xml` (and in fact discouraged to do so). It means, _an application ID simply doesn't exist at all anywhere in the world_. You are trying to find something that doesn't even exist.

If the local dev server requires an application ID, I think it makes much more sense to make the server accept an ID through a command-line argument, with which users may decide to provide some ID at the time of launching the server if they see fit. I think you should find a bug against the local dev server.

**Comment by chanseokoh** [comment]
Oh, wait, you're saying the maven plugin should set the system property "com.google.appengine.application.id" to "no_app_id"?

I wonder if you can't just assume "no_app_id" if the property is not defined.

**Comment by chanseokoh** [comment]
> Oh, wait, you're saying the maven plugin should set the system property "com.google.appengine.application.id" to "no_app_id"?

No, I figured out this isn't the case: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2235

**Comment by chanseokoh** [comment]
Discussions are going on in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2209. Since I am convinced this repo is not the right place to find a cure for the root problem, and to prevent fragmentation of discussions, I'll close this. We can always reopen later.
