### ISSUE TITLE
Make appengine scaling configurable

### ISSUE THREAD

**Issue by nilsonfreitas** [GoogleCloudPlatform/app-maven-plugin#203]
I have 2 projects on GAE, one I use for staging and the other for production. I have completely different scaling needs for both:

**staging**:
- Basic scaling
- Max instances: **1**

**prod**:
- Automatic scaling
- Min idle instances: **5**

Because this is not configurable, I have to run a script to walk through all _appengine-web.xml_ files and change the scaling type depending on where I am deploying.

The thing is: I forgot to run the script before publishing on staging a few weeks ago (off course this would happen),  deployed the wrong scaling type and got a huge bill this month (Yes I should have set up spending alerts but I didn't). 

Is there any elegant way of solving my problem? I just need the scaling type to be different depending on what project I am deploying.

If there is no elegant way I would like to propose this as a feature for app-maven-plugin.

Thanks

**Comment by patflynn** [comment]
@ludoch Ludo do you know how people usually manage this? 

I suppose one option would be to setup filtering on the appengine-web.xml with maven profiles to produce different values for prod vs staging.

**Comment by ludoch** [comment]
yep, either different appengine-web and a copy phase before compiling or
filtering

**Comment by nilsonfreitas** [comment]
I've applied your suggestions and it is working much better than my ugly script. For those who are having the same problem, here is what I did:

Add **dev** and **prod** profiles, similar to bellow:

```xml
<profiles>
    <profile>
      <id>dev</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <env>dev</env>
      </properties>
    </profile>
    <profile>
      <id>prod</id>
      <activation>
        <property>
          <name>env</name>
          <value>prod</value>
        </property>
      </activation>
      <properties>
        <env>prod</env>
      </properties>
    </profile>
  </profiles>
```
Inside your **WEB-INF** dorectory or any other location, create **prod** and **dev** folders and put the desired config files for each env. The result is something like:

- src/main/webapp/WEB-INF/prod/appengine-web.xml
- src/main/webapp/WEB-INF/dev/appengine-web.xml

You can also add the logging.properties if your settings differ between envs.

Then you can use *maven-resources-plugin* to copy the files depending on your env:
```xml
  <build>
    <outputDirectory>target/${project.artifactId}-${project.version}/WEB-INF/classes</outputDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-resources</id>
            <phase>validate</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>target/${project.artifactId}-${project.version}/WEB-INF/</outputDirectory>
              <resources>
                <resource>
                  <directory>src/main/webapp/WEB-INF/${env}</directory>
                  <filtering>true</filtering>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

Then you can switch between prod and dev from comand line, like bellow:

- mvn clean install -Denv=**prod**
- mvn clean install -Denv=**dev**

If **env** isn't specified it will default to **dev**.

Many thanks

**Comment by patflynn** [comment]
@nilsonfreitas thanks for sharing!
