### ISSUE TITLE
allow customization of service at deploy time...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/app-maven-plugin#204]
I don't know if any customers need this, but it would be very helpful to me.

I deploy a lot of samples during testing and it would be nice to be able to specify a specific service so I could test in a lot of places.

**Comment by loosebazooka** [comment]
Presumably you could do resource filtering in maven to customize the appengine-web.xml at build time? gcloud doesn't really have a provision for mentioning the service, it just reads it from app.yaml.

This would be similar to this question : https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/203

**Comment by patflynn** [comment]
@lesv I think there's a bug open against the Cloud SDK for this. As soon as they support it, we will add the ability to configure it.

**Comment by lesv** [comment]
Thanks - filtering in Maven wouldn't be a good idea in my case as they are published samples and it would only serve to make things more complex, which is the exact opposite of what I'm trying to do.
