### ISSUE TITLE
Error escape http_headers

### ISSUE THREAD

**Issue by Dmsjwxvp** [GoogleCloudPlatform/app-maven-plugin#206]
Hello.
I have an error deploying apps when appengine-web.xml tag <http_headers> contains single quotes.

For example: appengine-web.xml:

\<static-files>
    \<include path="/index.html" expiration="10m">
        \<http-header name="Content-Security-Policy" value="default-src * data: blob:; script-src **'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'** data:" />
        \</include>
\</static-files>

Appengine stage/deploy command generate app.yaml:

\- url: (/index\.html)
  http_headers:
    Content-Security-Policy: 'default-src * data: blob:; script-src **'self'' 'unsafe-inline'' 'unsafe-eval''; style-src 'self'' 'unsafe-inline''** data:'

The file contains two single quotes after self, unsafe-inline and unsafe-eval reserved names.

Similar issues:

https://issuetracker.google.com/issues/35899096
https://issuetracker.google.com/issues/35900597

It's possible fix this? Thank you so much.

**Comment by loosebazooka** [comment]
This would probably be in the appengine sdk yaml converter. @ludoch

**Comment by loosebazooka** [comment]
@Dmsjwxvp you might need to follow up on the google issue tracker for this, unfortunately the maven plugin cannot fix this.
