### ISSUE TITLE
(gcloud.app.deploy) Error Response: [13] Unexpected Error.

### ISSUE THREAD

**Issue by aug70** [GoogleCloudPlatform/app-maven-plugin#207]
Deploying to app engine with maven plugin fails!

```
mvn com.google.cloud.tools:appengine-maven-plugin:deploy -DskipTests=true
```

com.google.cloud.tools:appengine-maven-plugin version 1.3.1, goal deploy

```
[INFO] GCLOUD: d4498962e4fc: Pushed
[INFO] GCLOUD: latest: digest: sha256:1c2516746601c4fe68dac3507fe684380b122ebc1801e8dc234599825d3cfb89 size: 2416
[INFO] GCLOUD: DONE
[INFO] GCLOUD: ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[INFO] GCLOUD:
[INFO] GCLOUD: Updating service [default]...
[INFO] GCLOUD: .....................failed.
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Error Response: [13] Unexpected Error. ()
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

There's no error message?

**Comment by loosebazooka** [comment]
Any chance you can run `gcloud app deploy` directly on the maven plugin build output.

```
$ mvn appengine:stage
$ gcloud app deploy target/appengine-staging/app.yaml
```

This way we can isolate the error that gcloud is producing.

**Comment by loosebazooka** [comment]
@znewman01 any ideas or know someone who might have one?

**Comment by chanseokoh** [comment]
He seemed to make it work with a workaround from our internal bug: https://github.com/GoogleCloudPlatform/getting-started-java/issues/281#issuecomment-328572130

**Comment by briandealwis** [comment]
A user encountered this with [Cloud Tools for Eclipse](https://stackoverflow.com/questions/47455392/deployment-failed-error-gcloud-app-deploy-error-response-13-an-internal) too.

**Comment by drewinglis** [comment]
Per https://github.com/GoogleCloudPlatform/getting-started-java/issues/281#issuecomment-331550059, this should be fixed with the latest version of gcloud. (But please let us know if you've tried updating gcloud and it doesn't fix it.)

(I would close this bug but I don't seem to have the right permission bits to do so.)
