### ISSUE TITLE
Cannot find class com/google/appengine/repackaged/com/google/common/base/StringUtil 

### ISSUE THREAD

**Issue by chriszohno** [GoogleCloudPlatform/app-maven-plugin#212]
Hi, 

I switched to use this plugin to deploy my app engine app. I am getting this error at run time. An app engine class is missing, do you have any idea why? 

The same project works fine if I use old version of cloud tool to deploy. 

org.eclipse.jetty.servlet.ServletHandler doHandle: (ServletHandler.java:624) javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: com/google/appengine/repackaged/com/google/common/base/StringUtil at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:391) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)

**Comment by chriszohno** [comment]
My tools:

"gcloud version" output:

Google Cloud SDK 170.0.1
app-engine-java 1.9.54
app-engine-python 1.9.57
bq 2.0.25
core 2017.09.08
gcloud 
gsutil 4.27

**Comment by chriszohno** [comment]
If I deploy from my windows machine, everything is ok.
On Windows, "gcloud version" output:

Google Cloud SDK 122.0.0
bq 2.0.24
bq-win 2.0.24
bundled-python 2.7.10
core 2016.08.16
core-win 2016.08.05
gcloud
gsutil 4.20
gsutil-win 4.20
powershell 0.1.3
windows-ssh-tools 2016.05.13

**Comment by loosebazooka** [comment]
Try upgrading your tools on Mac to 171, I believe the repackaged dependency stuff is fixed in there.

**Comment by chriszohno** [comment]
I upgraded to latest my Mac to latest gcloud tools, but it still has the same issue. The same error:

javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: com/google/appengine/repackaged/com/google/common/base/StringUtil

$ gcloud version
Google Cloud SDK 173.0.0
app-engine-java 1.9.56
app-engine-python 1.9.60
bq 2.0.26
core 2017.09.25
gsutil 4.27
$ gcloud components update

All components are up to date.

**Comment by loosebazooka** [comment]
Perhaps @ludoch has an idea? Does it have something to do with jersey?

**Comment by ludoch** [comment]
Can you share your entire pom.xml to see which dep is using this repackaged class?
Or do you import it in your own code?

**Comment by chriszohno** [comment]
Thanks for your tips. I found a repackaged class is imported in my code.  I removed that and it works now. The strange thing is that if I deploy the same code from my Windows machine with old version of tools everything worked fine even with importing repackaged class.
