### ISSUE TITLE
Error: Running Cloud Endpoints on App Engine.

### ISSUE THREAD

**Issue by AxeemHaider** [GoogleCloudPlatform/app-maven-plugin#214]
I'm new in Google Cloud Platform, First time I'm going to setup Cloud Endpoint I Followed all instruction from [Getting Started with Endpoints Framework on AppEngine](https://cloud.google.com/endpoints/docs/frameworks/java/get-started-frameworks-java) Every thing is going well but when I run this command `mvn appengine:run` it will give error.

		Microsoft Windows [Version 6.1.7601]
	Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

	C:\Users\Azeem>cd C:\Users\Azeem\Downloads\gitClone\java-docs-samples\appengine\
	endpoints-frameworks-v2\backend

	C:\Users\Azeem\Downloads\gitClone\java-docs-samples\appengine\endpoints-framewor
	ks-v2\backend>mvn appengine:run
	[INFO] Scanning for projects...
	[INFO]
	[INFO] ------------------------------------------------------------------------
	[INFO] Building echo 1.0-SNAPSHOT
	[INFO] ------------------------------------------------------------------------
	[INFO]
	[INFO] >>> appengine-maven-plugin:1.3.1:run (default-cli) > package @ echo >>>
	[INFO]
	[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ echo ---
	[INFO] argLine set to -javaagent:C:\\Users\\Azeem\\.m2\\repository\\org\\jacoco\
	\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=C:\\Users\
	\Azeem\\Downloads\\gitClone\\java-docs-samples\\appengine\\endpoints-frameworks-
	v2\\backend\\target\\jacoco.exec
	[INFO]
	[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ echo ---
	[INFO] Using 'UTF-8' encoding to copy filtered resources.
	[INFO] skip non existing resourceDirectory C:\Users\Azeem\Downloads\gitClone\jav
	a-docs-samples\appengine\endpoints-frameworks-v2\backend\src\main\resources
	[INFO]
	[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ echo ---
	[INFO] Nothing to compile - all classes are up to date
	[INFO]
	[INFO] --- versions-maven-plugin:2.3:display-dependency-updates (default) @ echo
	 ---
	[INFO] No dependencies in Dependency Management have newer versions.
	[INFO]
	[INFO] The following dependencies in Dependencies have newer versions:
	[INFO]   javax.servlet:servlet-api ......................... 2.5 -> 3.0-alpha-1
	[INFO]
	[INFO]
	[INFO] --- versions-maven-plugin:2.3:display-plugin-updates (default) @ echo ---

	[INFO]
	[INFO] The following plugin updates are available:
	[INFO]   com.google.cloud.tools:endpoints-framework-maven-plugin  1.0.1 -> 1.0.2

	[INFO]
	[WARNING] The following plugins do not have their version specified:
	[WARNING]   maven-clean-plugin .......................... (from super-pom) 2.2
	[WARNING]   maven-compiler-plugin ..................... (from super-pom) 2.0.2
	[WARNING]   maven-deploy-plugin ......................... (from super-pom) 2.4
	[WARNING]   maven-install-plugin ........................ (from super-pom) 2.2
	[WARNING]   maven-resources-plugin ...................... (from super-pom) 2.2
	[WARNING]   maven-site-plugin .................... (from super-pom) 2.0-beta-4
	[WARNING]   maven-surefire-plugin ..................... (from super-pom) 2.4.2
	[INFO]
	[WARNING] Project does not define minimum Maven version, default is: 2.0
	[INFO] Plugins require minimum Maven version of: 3.0
	[INFO] Note: the super-pom from Maven 3.5.0 defines some of the plugin
	[INFO]       versions and may be influencing the plugins required minimum Maven
	[INFO]       version.
	[INFO]
	[ERROR] Project does not define required minimum version of Maven.
	[ERROR] Update the pom.xml to contain
	[ERROR]     <prerequisites>
	[ERROR]       <maven>3.0</maven>
	[ERROR]     </prerequisites>
	[INFO]
	[INFO] Require Maven 2.0.1 to use the following plugin updates:
	[INFO]   maven-war-plugin .............................................. 2.0.2
	[INFO]
	[INFO] Require Maven 2.0.2 to use the following plugin updates:
	[INFO]   maven-site-plugin ........................................ 2.0-beta-7
	[INFO]
	[INFO] Require Maven 2.0.6 to use the following plugin updates:
	[INFO]   maven-clean-plugin .............................................. 2.5
	[INFO]   maven-deploy-plugin ........................................... 2.8.1
	[INFO]   maven-install-plugin .......................................... 2.5.1
	[INFO]   maven-resources-plugin .......................................... 2.6
	[INFO]   maven-site-plugin ............................................. 2.0.1
	[INFO]   maven-surefire-plugin ......................................... 2.4.3
	[INFO]   maven-war-plugin ................................................ 2.4
	[INFO]
	[INFO] Require Maven 2.0.9 to use the following plugin updates:
	[INFO]   maven-compiler-plugin ........................................... 3.1
	[INFO]   maven-surefire-plugin .......................................... 2.17
	[INFO]
	[INFO] Require Maven 2.1.0 to use the following plugin updates:
	[INFO]   maven-site-plugin ............................................. 2.1.1
	[INFO]
	[INFO] Require Maven 2.2.0 to use the following plugin updates:
	[INFO]   maven-site-plugin ............................................... 3.0
	[INFO]
	[INFO] Require Maven 2.2.1 to use the following plugin updates:
	[INFO]   maven-clean-plugin ............................................ 2.6.1
	[INFO]   maven-compiler-plugin ........................................... 3.3
	[INFO]   maven-deploy-plugin ........................................... 2.8.2
	[INFO]   maven-install-plugin .......................................... 2.5.2
	[INFO]   maven-resources-plugin .......................................... 2.7
	[INFO]   maven-site-plugin ............................................... 3.4
	[INFO]   maven-surefire-plugin .......................................... 2.20
	[INFO]   maven-war-plugin ................................................ 2.6
	[INFO]   org.codehaus.mojo:versions-maven-plugin ......................... 2.2
	[INFO]
	[INFO] Require Maven 3.0 to use the following plugin updates:
	[INFO]   maven-clean-plugin ............................................ 3.0.0
	[INFO]   maven-compiler-plugin ......................................... 3.7.0
	[INFO]   maven-resources-plugin ........................................ 3.0.2
	[INFO]   maven-site-plugin ............................................... 3.6
	[INFO]   maven-surefire-plugin ........................................ 2.20.1
	[INFO]   maven-war-plugin .............................................. 3.1.0
	[INFO]   org.codehaus.mojo:versions-maven-plugin ......................... 2.5
	[INFO]
	[INFO]
	[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ec
	ho ---
	[INFO] Using 'UTF-8' encoding to copy filtered resources.
	[INFO] skip non existing resourceDirectory C:\Users\Azeem\Downloads\gitClone\jav
	a-docs-samples\appengine\endpoints-frameworks-v2\backend\src\test\resources
	[INFO]
	[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ echo --
	-
	[INFO] No sources to compile
	[INFO]
	[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ echo ---
	[INFO] No tests to run.
	[INFO]
	[INFO] --- jacoco-maven-plugin:0.7.9:report (report) @ echo ---
	[INFO] Skipping JaCoCo execution due to missing execution data file.
	[INFO]
	[INFO] --- maven-war-plugin:2.6:war (default-war) @ echo ---
	[INFO] Packaging webapp
	[INFO] Assembling webapp [echo] in [C:\Users\Azeem\Downloads\gitClone\java-docs-
	samples\appengine\endpoints-frameworks-v2\backend\target\echo-1.0-SNAPSHOT]
	[INFO] Processing war project
	[INFO] Copying webapp webResources [C:\Users\Azeem\Downloads\gitClone\java-docs-
	samples\appengine\endpoints-frameworks-v2\backend/src/main/webapp/WEB-INF] to [C
	:\Users\Azeem\Downloads\gitClone\java-docs-samples\appengine\endpoints-framework
	s-v2\backend\target\echo-1.0-SNAPSHOT]
	[INFO] Copying webapp resources [C:\Users\Azeem\Downloads\gitClone\java-docs-sam
	ples\appengine\endpoints-frameworks-v2\backend\src\main\webapp]
	[INFO] Webapp assembled in [161 msecs]
	[INFO] Building war: C:\Users\Azeem\Downloads\gitClone\java-docs-samples\appengi
	ne\endpoints-frameworks-v2\backend\target\echo-1.0-SNAPSHOT.war
	[INFO]
	[INFO] <<< appengine-maven-plugin:1.3.1:run (default-cli) < package @ echo <<<
	[INFO]
	[INFO]
	[INFO] --- appengine-maven-plugin:1.3.1:run (default-cli) @ echo ---
	Oct 03, 2017 9:55:53 AM com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEng
	ineDevServer1 run
	INFO: Setting appengine-web.xml configured environment variables: ENDPOINTS_SERV
	ICE_NAME=analog-premise-181709.appspot.com
	Oct 03, 2017 9:55:53 AM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCo
	mmand
	INFO: submitting command: C:\Program Files\Java\jdk1.8.0_144\jre\bin\java.exe -j
	avaagent:C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\googl
	e_appengine\google\appengine\tools\java\lib\agent\appengine-agent.jar -Dappengin
	e.sdk.root=C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\goo
	gle_appengine\google\appengine\tools\java -cp C:\Program Files (x86)\Google\Clou
	d SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\lib
	\appengine-tools-api.jar com.google.appengine.tools.development.DevAppServerMain
	 --allow_remote_shutdown --disable_update_check C:\Users\Azeem\Downloads\gitClon
	e\java-docs-samples\appengine\endpoints-frameworks-v2\backend\target\echo-1.0-SN
	APSHOT
	[INFO] GCLOUD: Oct 03, 2017 9:55:54 AM com.google.appengine.tools.development.Sy
	stemPropertiesManager setSystemProperties
	[INFO] GCLOUD: INFO: Overwriting system property key 'java.util.logging.config.f
	ile', value 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\g
	oogle_appengine\google\appengine\tools\java\config\sdk\logging.properties' with
	value 'WEB-INF/logging.properties' from 'C:\Users\Azeem\Downloads\gitClone\java-
	docs-samples\appengine\endpoints-frameworks-v2\backend\target\echo-1.0-SNAPSHOT\
	WEB-INF\appengine-web.xml'
	[INFO] GCLOUD:
	[INFO] GCLOUD: ************************************************
	[INFO] GCLOUD: Could not open the requested socket: Address already in use: bind

	[INFO] GCLOUD: Try overriding --address and/or --port.
	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD FAILURE
	[INFO] ------------------------------------------------------------------------
	[INFO] Total time: 8.192 s
	[INFO] Finished at: 2017-10-03T09:55:54-07:00
	[INFO] Final Memory: 27M/322M
	[INFO] ------------------------------------------------------------------------
	[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3
	.1:run (default-cli) on project echo: Execution default-cli of goal com.google.c
	loud.tools:appengine-maven-plugin:1.3.1:run failed: Non zero exit: 2 -> [Help 1]

	[ERROR]
	[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
	ch.
	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
	[ERROR]
	[ERROR] For more information about the errors and possible solutions, please rea
	d the following articles:
	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutio
	nException

	C:\Users\Azeem\Downloads\gitClone\java-docs-samples\appengine\endpoints-framewor
	ks-v2\backend>

Is there anything I miss ???

**Comment by patflynn** [comment]
Hi @AxeemHaider!

It appears as though the devappserver port is already in use.  Perhaps a previous run failed to shutdown cleanly.   It appears as though you're using Windows so you may want to take a look at your task manager (ctrl-alt-del) and see if there are any java processes open to kill.

you should be able to also run `netstat` from the command line to see what processes are using what ports.
