### ISSUE TITLE
Look at both src/main/docker/Dockerfile and src/main/appengine/Dockerfile

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/app-maven-plugin#22]
src/main/docker has priority
src/main/appengine is for legacy support

**Comment by loosebazooka** [comment]
see Gradle : https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/11

**Comment by meltsufin** [comment]
Just to clarify, currently the maven plugin defaults to looking in: `src/main/appengine/Dockerfile`.
