### ISSUE TITLE
enableJarClasses not being respected

### ISSUE THREAD

**Issue by jason-elmore** [GoogleCloudPlatform/app-maven-plugin#223]
I'm trying to deploy a project with Eclipse and the build seems to not be respecting my setting for jarring my classes.

Here is the message I get in the console:
```
INFO: We detected that you have a large number of .class files in WEB-INF/classes. You may be able to reduce request latency by packaging your .class files into jars. To do this, supply the --enable_jar_classes flag when using appcfg on command line. If you're using the Cloud SDK based app-maven-plugin, add <stage.enableJarClasses>true</stage.enableJarClasses> in the plugin's <configuration> tag. If you are using the AppCfg based appengine-maven-plugin, supply <enableJarClasses>true</enableJarClasses> in the plugin's <configuration> tag. Note that this flag will put the jar in WEB-INF/lib rather than WEB-INF/classes. The classloader first looks in WEB-INF/classes and then WEB-INF/lib when loading a class. As a result, this flag could change classloading order, which may affect the behavior of your app.
```

Here is the build element from my pom.xml

```xml
<build>
    <!-- for hot reload of the web application-->
    <outputDirectory>${project.build.directory}/${project.build.finalName}/WEB-INF/classes</outputDirectory>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>versions-maven-plugin</artifactId>
        <version>2.3</version>
        <executions>
          <execution>
            <phase>compile</phase>
            <goals>
              <goal>display-dependency-updates</goal>
              <goal>display-plugin-updates</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>${appengine.maven.plugin.version}</version>
        <configuration>
        <stage.enableJarClasses>true</stage.enableJarClasses>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

**Comment by loosebazooka** [comment]
It's possible your cloud sdk is out of date. I believe this was fixed. Can you post the output of
```
gcloud version
```
or even better, just update to latest and try it out:
```
gcloud components update
```

**Comment by jason-elmore** [comment]
I'm all up to date.

Google Cloud SDK 177.0.0
app-engine-java 1.9.58
app-engine-python 1.9.62
bq 2.0.27
core 2017.10.20
gcloud 
gsutil 4.28

**Comment by loosebazooka** [comment]
That's so strange, just so I'm clear, are you using eclipse or maven to deploy?

**Comment by jason-elmore** [comment]
I'm using Eclipse to deploy.

**Comment by loosebazooka** [comment]
oh. Using "Google Plugin for Eclipse" or "Cloud tools for Java"?

**Comment by jason-elmore** [comment]
![screen shot 2017-10-25 at 2 14 06 pm](https://user-images.githubusercontent.com/1048295/32023677-d62b9460-b98e-11e7-847c-87e5870fe7e0.png)

**Comment by loosebazooka** [comment]
I believe if you use maven to deploy (or stage), it will jar up your classes fine and deploy.
```
$ mvn appengine:stage
```
then inspect `/target/appengine-staging/WEB-INF/libs` and you should see the classes jar'd up.

Since you're using eclipse BUT configuring using maven, you're going to have some issues with synchrony. If you're using maven to configure, I would suggest you use maven for deployment. Or you can ask on the eclipse project page for more details : https://github.com/GoogleCloudPlatform/google-cloud-eclipse

**Comment by loosebazooka** [comment]
Can you file this against the eclipse plugin if you're still experiencing issues?
