### ISSUE TITLE
How do we vary the instance class?

### ISSUE THREAD

**Issue by stickfigure** [GoogleCloudPlatform/app-maven-plugin#227]
The old maven plugin would perform variable substitutions on `appengine-web.xml`. This allows us to vary the instance class for different deployment environments using maven properties like this:

```
    <instance-class>${appengine.instance.class}</instance-class>
```

The new maven plugin does not appear to do this substitution. How can I use F1 instances for my sandbox environment, but F2 or F4 instances for my production environment? I don't see anything related to instance class in the maven deploy parameters or gcloud app deploy help.

**Comment by loosebazooka** [comment]
How were you doing it before? We don't anything special for filtering on war creation, perhaps there is a maven plugin that allows you do this?
Maybe something like this?
https://maven.apache.org/plugins/maven-war-plugin/examples/adding-filtering-webresources.html

**Comment by stickfigure** [comment]
Ah! That was it - sorry about the noise. Thanks.
