### ISSUE TITLE
Please allow the ability to configure ports for services other that the default service

### ISSUE THREAD

**Issue by the-rockkk** [GoogleCloudPlatform/app-maven-plugin#235]
In a multi-service GAE project, when debugging using the Cloud Tools Plugin for Eclipse, it would be very useful to be able to assign specific ports to the services other than the default service, instead of the server code assigning random ports.

**Comment by loosebazooka** [comment]
I do not believe that is a feature of the dev appserver, if you would like you can file a bug against the app engine SDK : https://issuetracker.google.com/issues/new?component=187272&template=1010421

**Comment by branks** [comment]
You can do this using JVM flags like so:

 jvmFlags = [
        "-Dcom.google.appengine.devappserver_module.default.port=8080",
        "-Dcom.google.appengine.devappserver_module.XXXXXXX.port=8081",
    ]

where XXXXX is the name of your other module
