### ISSUE TITLE
devServer doesn't respect project id

### ISSUE THREAD

**Issue by eschultink** [GoogleCloudPlatform/app-maven-plugin#236]
Attempting to migrate from the appcfg-based Maven plugin to the gcloud based on, I get the following message:
``` 
INFO: Application id 'localdevapp' from '/var/folders/q5/ysbzrm957jx8yllsvymqwkhm0000gn/T/tmpEarArea7331600631430393319/META-INF/appengine-application.xml' is overriding  application id 'app-staging' from '/Users/user/code/app/module-default/target/module-default-1.0-SNAPSHOT/WEB-INF/appengine-web.xml'
```
In dev, we use some cloud resources from our staging project. If the dev server can't get the proper project id, these aren't accessible.

I'm running the dev server with `mvn appengine:run` directly from the root of our default module, which is packaged as a WAR and has the following plugin config:
```xml
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>appengine-maven-plugin</artifactId>
                <version>${maven.appengine.plugin-version}</version>
                <configuration>
                    <project>${appengine.app.projectid}</project>
                    <version>${module.version}</version>
                    <services>
                        <service>${targetDirectory}</service>
                        <service>${project.parent.basedir}/module-i/target/module-i-${project.version}</service>
                        <service>${project.parent.basedir}/module-j/target/module-j-${project.version}</service>
                    </services>
                    <devserver.host>dev.local</devserver.host>
                </configuration>
            </plugin>
```

It appears that the Maven plugin is building an EAR behind the scenes, given that the file path it's looking in is called `tmpEarArea` and reference to `EarHelper`?
```
Dec 14, 2017 6:15:43 AM com.google.apphosting.utils.config.EarHelper readEarInfo
```

This is confusing, because [configuration files documentation](https://cloud.google.com/appengine/docs/standard/java/configuration-files) specifically says that Java 8 runtime does NOT support EAR?  And migration walk-through seems consistent with that, saying to EAR's `application.xml` to the above structure.

**Comment by patflynn** [comment]
Hi @eschultink,

Thanks for your detailed report on this issue. 

Which libraries are you using to use cloud resources in a staging project?  You can configure your google-cloud-java libraries project ID using the `GOOGLE_CLOUD_PROJECT` environment variable. 

Is it possible you have an appengine-application.xml in your project?  That may be why you're still seeing ear related messages.

@loosebazooka I'm wondering if it would make sense to have `app.devserver.project` and `app.devserver.version` fields that we can pass through to the devserver for local run.

**Comment by chanseokoh** [comment]
> It appears that the Maven plugin is building an EAR behind the scenes, given that the file path it's looking in is called tmpEarArea and reference to EarHelper?
>
> This is confusing, because configuration files documentation specifically says that Java 8 runtime does NOT support EAR? And migration walk-through seems consistent with that, saying to EAR's application.xml to the above structure.

You're right that you won't be deploying an EAR. Rather, you'll deploy individual services, as you would expect. FWIW, the EAR-related things you see are just an implementation detail of the local dev app server that you don't need to know about. The design the local server adopted to support emulating the prod environment with multiple services is to package all the services up as an EAR internally, if I'm not mistaken.

**Comment by eschultink** [comment]
Thanks for the quick response! 

> Which libraries are you using to use cloud resources in a staging project? You can configure your google-cloud-java libraries project ID using the `GOOGLE_CLOUD_PROJECT` environment variable.

@patflynn main cloud service we use that can't be emulated locally is BigQuery. Not sure if there is a solution to this now?  At a glance, I don't see one.  We also use CloudKMS, but that's less critical for dev purposes.

`GOOGLE_CLOUD_PROJECT` env variable is an inelegant solution (what if am working with multiple projects on my machine?), but also does not seem to work:

```
[INFO] --- appengine-maven-plugin:1.3.2:run (default-cli) @ module-frontend ---
Dec 14, 2017 9:47:25 AM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/bin/java -Duse_jetty9_runtime=true -D--enable_all_permissions=true -Dappengine.sdk.root=/Users/erik/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java -cp /Users/erik/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com.google.appengine.tools.development.DevAppServerMain --address=worklytics.dev --allow_remote_shutdown --disable_update_check --no_java_agent /Users/erik/code/app/module-frontend/target/module-frontend-1.0-SNAPSHOT /Users/erik/code/app/module-i/target/module-i-1.0-SNAPSHOT /Users/erik/code/app/module-j/target/module-j-1.0-SNAPSHOT
[INFO] GCLOUD: Dec 14, 2017 9:47:27 AM com.google.apphosting.utils.config.EarHelper readEarInfo
[INFO] GCLOUD: INFO: Application id 'localdevapp' from '/var/folders/q5/ysbzrm957jx8yllsvymqwkhm0000gn/T/tmpEarArea6330381304610172336/META-INF/appengine-application.xml' is overriding  application id 'app-staging' from '/Users/erik/code/app/module-frontend/target/module-frontend-1.0-SNAPSHOT/WEB-INF/appengine-web.xml'
```
...

```sh
embp:module-frontend erik$ echo $GOOGLE_CLOUD_PROJECT
worklytics-staging
```



> Is it possible you have an appengine-application.xml in your project? That may be why you're still seeing ear related messages.

Yes, I still had `appengine-application.xml` lying around, but out of target WAR directory. The [migration guide](https://cloud.google.com/appengine/docs/standard/java/tools/migrate-maven) says NOT to delete the EAR until you have the new plugin working 😛 . I don't think it was being used though - even when I remove it entirely now, I still see log info about readEarInfo etc.  So I think as @chanseokoh said, it's implementation detail. I just wanted to make sure it was expected behavior, rather than my project not being migrated correctly.

**Comment by eschultink** [comment]
@patflynn I can't find documentation to support the `GOOGLE_CLOUD_PROJECT` environment variable solution.  It seems this type of thing is done with `gcloud config` - see https://cloud.google.com/sdk/docs/managing-configurations. 

But mine was already set to my production project ID, so I don't think the dev server is using that value either.
![bash 2017-12-14 10-04-27](https://user-images.githubusercontent.com/102831/34007533-fd8cef5a-e0b6-11e7-9b33-540723bd67f7.png)

**Comment by patflynn** [comment]
@eschultink could you point me to the BigQuery library you're using from your App Engine app?

**Comment by chanseokoh** [comment]
> I don't think it was being used though - even when I remove it entirely now, I still see log info about readEarInfo etc. So I think as @chanseokoh said, it's implementation detail. I just wanted to make sure it was expected behavior, rather than my project not being migrated correctly.

@patflynn @eschultink indeed, the `appengine-application.xml` is an implementation detail for the local server to support multiple services. Below is a log from running two trivial hello-world services, neither of which is an EAR or a part of an EAR. It seems to auto-generate `appengine-application.xml` with a preset `localdevapp` ID when internally packaging an EAR to run multiple services locally. Maybe it is the limitation of the local dev server. @ludoch?

```
Dec 14, 2017 1:43:35 PM com.google.apphosting.utils.config.EarHelper readEarInfo
INFO: Application id 'localdevapp' from '/tmp/tmpEarArea3876982147705783885/META-INF/appengine-application.xml' is overriding  application id 'null' from '<redacted>/tmp0/hello-world-A/WEB-INF/appengine-web.xml'
Dec 14, 2017 1:43:35 PM com.google.apphosting.utils.config.EarHelper readEarInfo
INFO: Application id 'localdevapp' from '/tmp/tmpEarArea3876982147705783885/META-INF/appengine-application.xml' is overriding  application id 'null' from '<redacted>/hello-world-B/WEB-INF/appengine-web.xml'
Dec 14, 2017 1:43:35 PM com.google.appengine.tools.development.DevAppServerImpl <init>
INFO: Ignoring application.xml context-root element, for details see https://developers.google.com/appengine/docs/java/modules/#config
```

**Comment by eschultink** [comment]
@patflynn https://developers.google.com/api-client-library/java/apis/bigquery/v2 (we're using v2-rev350-1.22.0, but I doubt that's relevant; seems reasonably recent)  

The `projectId` is passed in programmatically. We parse it from `SystemProperty.applicationId.get()`; in GAE standard environment, that is your projectId; and it should be in the dev server too.  But in this case the dev server is setting that to `localdevenv` or whatever right now - rather than respecting the `project` value defined in the plugin configuration, which seems only used for deploy?

**Comment by patflynn** [comment]
@eschultink 

That's correct.  The plugin project configuration is for deployment only.  

@ludoch the setting of application id as 'localdevenv' for multi-module runs seems like a problem here.  @loosebazooka  In addition we need a better UX story for tooling to set the local project ID.

**Comment by Trii** [comment]
This also seems to affect namespacing of entities in your local datastore.

**Comment by Trii** [comment]
This seems to happen if you supply more than one entry for `<service>`

**Comment by loosebazooka** [comment]
I'll see what we can do to provide an elegant solution to this.

**Comment by eschultink** [comment]
@loosebazooka - still fighting with this. Any update? 

Is this plugin supported by Google still? 

I had interpreted the docs (such as https://cloud.google.com/appengine/docs/standard/java/tools/migrate-maven) to imply that this plugin was the future direction of the tooling.  But perhaps we need to migrate back to the other plugin (https://github.com/GoogleCloudPlatform/appengine-maven-plugin) as that seems to be more actively maintained?

**Comment by loosebazooka** [comment]
Sorry for the delay. Will try to find someone to do this on the sdk side.

**Comment by ryantgraham** [comment]
I've recently run into this issue when migrating an app to use multi-modules/services. Any word on if or when this might be addressed?

**Comment by loosebazooka** [comment]
This should be address is the next 2.0.0-rc (this week), and will be finalized in the 2.0.0 final release.
