### ISSUE TITLE
Where is the documentation for the plugin describing pom.xml configuration?

### ISSUE THREAD

**Issue by Trii** [GoogleCloudPlatform/app-maven-plugin#239]
I can't find the documentation on fields like `<deploy.project></deploy.project>` that are available in the `<plugin>` definition. Where is that?

**Comment by patflynn** [comment]
@Trii is [this](https://cloud.google.com/appengine/docs/standard/java/tools/maven-reference) what you're looking for?

**Comment by Trii** [comment]
@patflynn kinda, except it is wrong.

The example shows this:
```
<configuration>
       <stage.enableJarSplitting>true</stage.enableJarSplitting>
       <deploy.stopPreviousVersion>true</deploy.stopPreviousVersion>
       <cloudSdkPath>/usr/foo/path/to/cloudsdk</cloudSdkPath>
     </configuration>
```

But there aren't any parameters labeled `deploy.stopPreviousVersion` anywhere on the page. There is `app.deploy.stopPreviousVersion` and `app.deploy.project`. I found `deploy.project` via autocomplete in IntelliJ.

Based on your comment, it looks like I can try some version of the `app.*` user properties in my pom.xml by removing the prefix `app.`. Is that correct?

**Comment by patflynn** [comment]
@Trii I believe there are shorthand aliases that allow you to remove the app.  @loosebazooka to confirm.

**Comment by loosebazooka** [comment]
Yeah. Looks like we need to fix these docs a little.

**Comment by parkjam4** [comment]
@loosebazooka, sure. Can you create a nug with what changes you need to the page? Thanks

**Comment by Trii** [comment]
I tried using the `app.` prefix in the pom and those do not work in case that helps in the documentation update. e.g. `<app.deploy.version></app.deploy.version>` is a no-go.

**Comment by loosebazooka** [comment]
I see, @Trii, looks like we're not correctly reflecting the configuration of `alias` (pom.xml reference name) vs `property` (command line reference name). I'll have to update the docs to reflect that correctly. Please just use the non-"app" version of the properties till the docs are updated. Thanks for bringing this our attention.

**Comment by Trii** [comment]
Thank you @loosebazooka - I love the new plugin so far. Having some hiccups with it, but it may be in migrating from an old project to the new plugin
