### ISSUE TITLE
More than one entry for app.devserver.services overrides project ID

### ISSUE THREAD

**Issue by Trii** [GoogleCloudPlatform/app-maven-plugin#242]
I noticed today that the local appserver uses the project ID I specify in my service's appengine-web.xml when I run it stand alone, but when I try to run 2 or more services, it overrides it to `localdevapp`

These both use my app ID from appengine-web.xml:

* `mvn com.google.cloud.tools:appengine-maven-plugin:run`
* `mvn com.google.cloud.tools:appengine-maven-plugin:run -Dapp.devserver.services=target/my-service-1-1.0.0`

This overrides my app ID to `localdevapp`:
* `mvn com.google.cloud.tools:appengine-maven-plugin:run -Dapp.devserver.services=target/my-service-1-1.0.0,../my-service-2/target/my-service-2-1.0.0`

Related to #236

**Comment by loosebazooka** [comment]
You can now specify "projectId" on multimodule runs to override the project.
