### ISSUE TITLE
appengine:start doesn’t respect appYamls or services

### ISSUE THREAD

**Issue by denisa** [GoogleCloudPlatform/app-maven-plugin#243]
during appengine:start, the plugin checks if the application is a standard application or not.
It is hard-coded to check for WEB-INF/appengine-web.xml in ${project.build.directory}/${project.build.finalName},  the build directory of the current project.

It should look for the WEB-INF/appengine-web.xml under the configured appYamls or services

Use case:
I have a multi-module project in maven with an ‘application’ and one or more ‘integration’ modules. ‘application' builds the war, the ‘integration’ modules run various integration tests.
It’s not possible to launch the app from the ‘integration’ modules.

**Comment by loosebazooka** [comment]
I think you'll have to use the workaround of putting a dummy appengine-web.xml in your "integration" project for now.

**Comment by loosebazooka** [comment]
marking obselete. Java will be devappserver1 only from #378
