### ISSUE TITLE
Include all files under src/main/appengine in the staging directory

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/app-maven-plugin#25]
Currently, only `Dockerfile` and `app.yaml` are copied over. We should copy all files over.

For example, the alpha version of Endpoints requires a `swagger.json` or `swagger.yaml` file to be alongside the `app.yaml`.

**Comment by broady** [comment]
cc @ludoch @lesv

**Comment by patflynn** [comment]
The swagger files aren't appengine specific are they?  Shouldn't they go
under resources?

**Comment by broady** [comment]
In this case, the location is specific to App Engine (actually, `gcloud app`).

They must not be bundled into the WAR file.

**Comment by lesv** [comment]
If you put them in `src/main/resources/` they will be and can be found on the classpath.

**Comment by meltsufin** [comment]
I assume this only applies to staging for flexible environment deployment. Currently, the plugin takes an `app.yaml` path as a parameter. Should we instead have an `appengineDirectory` path as a parameter?

**Comment by meltsufin** [comment]
Related issue in common tools list: GoogleCloudPlatform/app-tools-lib-for-java/issues/96

**Comment by broady** [comment]
Any update here? Is this a reasonable thing to do?

**Comment by meltsufin** [comment]
Work in progress: https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/pull/127

**Comment by meltsufin** [comment]
Fixed by GoogleCloudPlatform/app-tools-lib-for-java#127
