### ISSUE TITLE
app-maven-plugin vs appengine-maven-plugin

### ISSUE THREAD

**Issue by hshang09** [GoogleCloudPlatform/app-maven-plugin#260]
What's the difference between app-maven-plugin and appengine-maven-plugin (https://github.com/GoogleCloudPlatform/appengine-maven-plugin)? 

When to use which?

**Comment by chanseokoh** [comment]
`com.google.cloud.tools.appengine-maven` is the new plugin based on the Cloud SDK. The difference is explained in this doc: https://cloud.google.com/appengine/docs/standard/java/tools/migrate-maven

If the new plugin covers all your needs, we recommend using the new one.

**Comment by hshang09** [comment]
I see. Thank you @chanseokoh.
