### ISSUE TITLE
Hot reload is not working with Google App Engine Standard Maven Projects

### ISSUE THREAD

**Issue by jamesmortensen** [GoogleCloudPlatform/app-maven-plugin#266]
If I create a project using the Cloud Tools for Eclipse plugin, and then I check the checkbox to create a Maven project, the hot swapping features of the App Engine Dev Server are not working.  

There is no documentation on how to enable this, and it doesn't appear to be a default.  Can we get this added as a default feature so we aren't swapping out one headache (no dependency management) with another (no hot swapping).

Thank you,

**Comment by chanseokoh** [comment]
@jamesmortensen just to confirm, the hot reload does and should work when you run the server inside Eclipse. You are talking about running the server using the Maven plugin outside Eclipse, aren't your?

https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/USER_GUIDE.md#how-do-i-enable-hot-reload-of-my-application

You can set the value to 1 second.

**Comment by jamesmortensen** [comment]
@chanseokoh Thanks for the relevant link.  I got this working now for a default Maven project as well as Spring Boot App Engine project.  The server restart is so slow though in Spring Boot, and it seems like it's trying to reload everything instead of just swapping out compiled class files into the running JVM.  (I thought traditional hot swap just swapped in class files without needing to do a full restart).

- Do you think there a more advanced hot swap, or is it just slow because of Spring?

- Is there any reason why hot reload couldn't be a sensible default for development for Google App Engine Standard projects?  For instance, could we add that to the "How to use" section on the main README.md?  https://github.com/GoogleCloudPlatform/app-maven-plugin

Thanks again for the help and answering my questions,
James

**Comment by patflynn** [comment]
@loosebazooka 
@chanseokoh 

For hotswap behavior you need to turn off reload and use an IDE to debug and incrementally build into the exploded app directory.   appengine.fullscan.seconds=5 will actually break a good hotswap setup by restarting the JVM each time.  We should probably not recommend that as a development workflow.

**Comment by chanseokoh** [comment]
Yeah, I actually recommend debugging in Eclipse, as the hot swap you are talking  about is already set up. That said, the hot swap in IDEs only works when launching a debug session. The hot swap will be much faster than the server restart, as you can expect. BTW, in Eclipse, we still try to provide hot reload (not hot swap) in a non-debug session too by setting -Dappenigne.fullscan.seconds=1 for convenience, since some developers said doesn't like running in debug as it is too slow.

**Comment by sumitkanoje** [comment]
@chanseokoh I'm getting `java.lang.AbstractMethodError: ` while hot swapping when I replace a jar file into projects target directory in IntelliJ

```
[INFO] GCLOUD: Aug 11, 2019 8:33:04 PM com.google.appengine.tools.development.jetty9.JettyContainerService$2 filesChanged
[INFO] GCLOUD: INFO: A file has changed, reloading the web application.
[INFO] GCLOUD: 2019-08-11 20:33:04.731:INFO:oejsh.ContextHandler:Scanner-0: Stopped c.g.a.t.d.j.DevAppEngineWebAppContext@775f15fd
[INFO] GCLOUD: 2019-08-11 20:33:04.731:WARN:oeju.Scanner:Scanner-0: com.google.appengine.tools.development.jetty9.JettyContainerService$2@36055562 failed on '[/Users/sumit/Documents/Work/idea-workspace/my-app/gcp-app/target/gcp-app-1.0.0-SNAPSHOT/WEB-INF/lib/gcp-commons-1.0.0-SNAPSHOT.jar]
[INFO] GCLOUD: java.lang.AbstractMethodError: org.apache.tomcat.websocket.server.WsFilter.destroy()V
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.FilterHolder.destroyInstance(FilterHolder.java:175)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.FilterHolder.doStop(FilterHolder.java:152)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletHandler.doStop(ServletHandler.java:246)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:178)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:199)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
[INFO] GCLOUD: 	at org.eclipse.jetty.security.SecurityHandler.doStop(SecurityHandler.java:381)
[INFO] GCLOUD: 	at org.eclipse.jetty.security.ConstraintSecurityHandler.doStop(ConstraintSecurityHandler.java:457)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:178)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:199)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.session.SessionHandler.doStop(SessionHandler.java:583)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:178)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:199)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:932)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:376)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.stopWebapp(WebAppContext.java:1503)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1467)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:1009)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:288)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:569)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:178)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:199)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.jetty9.JettyContainerService.reloadWebApp(JettyContainerService.java:485)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.jetty9.JettyContainerService$2.filesChanged(JettyContainerService.java:469)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.reportBulkChanges(Scanner.java:686)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:540)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner$1.run(Scanner.java:329)
[INFO] GCLOUD: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[INFO] GCLOUD: 	at java.util.TimerThread.run(Timer.java:505)
```

Any clues around why is this happening?

**Comment by sumitkanoje** [comment]
thanks @chanseokoh I figured it out gcp-commons-1.0.0-SNAPSHOT.jar was having dependency on some tomcat jar(which might be getting conflicted with jetty). After adding tomcat in exclusion I was able to achieve hot swapping.

**Comment by kyletheninja** [comment]
I'm having a similarish problem with my webapp folder when I try to edit files in vscode. I like to use eclipse for java coding and git integration, but vscode for my web files. However with this app-engine server it seems to cache my web files or something because I have to actually go into eclipse and refresh them before reloading my browser will pull the versions which has been saved from vscode.

`<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">

  <threadsafe>true</threadsafe>
  <sessions-enabled>false</sessions-enabled>
  <runtime>java8</runtime>

  <system-properties>
    <property name="java.util.logging.config.file" value="WEB-INF/logging.properties"/>
  </system-properties>

</appengine-web-app>`

When I use an embedded jetty server like I'm used to this problem disappears but I haven't figured out how to deploy that as is simple when using the standard app-engine.

**Comment by loosebazooka** [comment]
@kyletheninja can you open a new issue? And include your pom file?

**Comment by kyletheninja** [comment]
Can't find a POM, my bad. I must be in the wrong place. I'm trying to use the "Google App Engine Standard Java Project" or the "Google App Engine Flexible Java Project". So I think its not your problem but if you happen to recognize what's going on here, should I just be using this maven plugin? All I really want is a java webserver that servers static content and rest API which I can deploy with my Google Cloud Platform.

**Comment by briandealwis** [comment]
Sorry @kyletheninja I missed this. Eclipse has a preference to enable auto refresh of externally-modified files at _Preferences > General > Workspace > Refresh using native hooks or polling_. Make sure it is enabled.

(You might also want to check out the [Eclipse Wild Web Developers plug-in](https://github.com/eclipse/wildwebdeveloper/blob/master/README.md), which uses the VS Code HTML, CSS, and JSON language servers under the hood.)

**Comment by kyletheninja** [comment]
Aha, thank you very much sir.

**Comment by chanseokoh** [comment]
`war:exploded` is a goal of the Maven War plugin that does something else. You want `appengine:run` for the App Engine plugin to start a dev server. I expect it should work then.

But I think it's conflicting to have both
```xml
	<automaticRestart>true</automaticRestart>
```
and
```xml
		<jvmFlag>-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n</jvmFlag>
```
as [explained earlier](https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/266#issuecomment-377246624). Most of the time, debugging through JDWP should be enough and provide better experience.

---

I think there's nothing to be done for this issue, so closing. It's documented how to do automatic restarts or set up debugging, and we are not going to change the current default.
