### ISSUE TITLE
Set percentage traffic

### ISSUE THREAD

**Issue by AngelLuisSanchez** [GoogleCloudPlatform/app-maven-plugin#289]
Hi again!

Is it possible to set percentage traffic when I deploy with maven plugin?

In addition to Readme, is there any other documentation?

Thanks!

**Comment by TadCordle** [comment]
>In addition to Readme, is there any other documentation?

The [user guide](https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/USER_GUIDE.md) is much more detailed than the readme. Also the appengine documentation [here](https://cloud.google.com/appengine/docs/standard/java/tools/maven) may help.

Not sure about percentage traffic, maybe @loosebazooka can help.

**Comment by AngelLuisSanchez** [comment]
Don't worry about it, I've already found a solution.

Previously, I set traffic split in console.cloud.google by 50 per cent.
In plug-in block, I set promote to false to avoid set all traffic to new version.

That's all.

Thanks anyway!
