### ISSUE TITLE
App engine deploymemt failure

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/app-maven-plugin#296]
I am getting below error while deploying maven project to GCP through bitbucket pipeline.
Here is my bitbucket project

https://bitbucket.org/ad_tech/bigqueryrepo.git

This is the entire logs:

[pipelineLog-20.txt](https://github.com/GoogleCloudPlatform/app-maven-plugin/files/1937652/pipelineLog-20.txt)

here is a gist of the error:
[INFO] GCLOUD: ERROR: gcloud crashed (UnicodeEncodeError): 'ascii' codec can't encode characters in position 22-23: ordinal not in range(128)
[INFO] GCLOUD: 
[INFO] GCLOUD: If you would like to report this issue, please run the following command:
[INFO] GCLOUD:   gcloud feedback
[INFO] GCLOUD: 
[INFO] GCLOUD: To check gcloud for common problems, please run the following command:
[INFO] GCLOUD:   gcloud info --run-diagnostics
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.464 s
[INFO] Finished at: 2018-04-23T10:08:44Z
[INFO] Final Memory: 38M/625M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3.1:deploy (default-cli) on project samplebigquery: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.3.1:deploy failed: Non zero exit: 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3.1:deploy (default-cli) on project samplebigquery: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.3.1:deploy failed: Non zero exit: 1

**Comment by chanseokoh** [comment]
Looks like the direct cause is that there is a non-ascii character somewhere (in a username, contents in `app.yaml` or `appengine-web.xml`, or file path) or the OS is running the `gcloud` program in a certain language setting. Please take a look at these and see if you can resolve the issue:

https://issuetracker.google.com/72210213
https://issuetracker.google.com/37955039

**Comment by chanseokoh** [comment]
I see https://issuetracker.google.com/37955039 is marked fixed. Hopefully the issue is resolved.

**Comment by codler** [comment]
I had the same error and I found out it was because a filenamn contained åäö
