### ISSUE TITLE
Add a 2.0-release candidate warning when plugin is loaded

### ISSUE THREAD

**Issue by TadCordle** [GoogleCloudPlatform/app-maven-plugin#298]
Mirror of https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/257

**Comment by patflynn** [comment]
I don't really object to his, but just thought I'd mention that I wouldn't
expect this as an end user.

they had to explicitly configure the plugin version to use it so I should
know it's an RC candidate.

**Comment by loosebazooka** [comment]
Hrmm.... maybe it's more of a concern to gradle users who can do "com.plugin:plugin:+"?

**Comment by patflynn** [comment]
Oh would that + include an RC over a GA version?

**Comment by loosebazooka** [comment]
no, but I believe it would pick up `2.0.0-rc1` over `1.3.6`

**Comment by TadCordle** [comment]
Going to close this since it sounds like this isn't needed for the maven plugin, feel free to reopen if you think there's more discussion to be had (or we can use the corresponding [gradle plugin issue](https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/257)).
