### ISSUE TITLE
appengine:run no auto generated indexes, doesn't pickup datastore-indexes.xml on local development server

### ISSUE THREAD

**Issue by jfinci1** [GoogleCloudPlatform/app-maven-plugin#304]
This is a help request

Building a web server with Java/Spring, Gcloud SDK, and Appengine maven

Referencing this issue: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/134

I seem to be unable to query datastore with the local development server as indexes are not auto-generating and my datastore-indexes.xml seems to be ignored- I'm generally confused/lost on how to get this to work locally.  Deploying to a dev environment for every iteration would be a bit of a pain

I've attempting renaming the datastore-indexes.xml to just datastore-index.xml, indexes.xml, index.xml

Current directory structure I believe is correct src/main/java/webapp/WEB-INF/datastore-indexes.xml

Any help would be greatly appreciated. Thanks!

**Comment by chanseokoh** [comment]
Hi @jfinci1,

Below is an example project with `datastore-indexes.xml`:

[datastore-index-test.zip](https://github.com/GoogleCloudPlatform/app-maven-plugin/files/1975514/datastore-index-test.zip)

1. Download the zip file.
1. `$ unzip datastore-index-test.zip && cd datastore-index-test`
1. `$ mvn clean appengine:run`
1. Access http://localhost:8080/_ah/admin
1. Click "Show Indexes".
![selection_011](https://user-images.githubusercontent.com/10523105/39646000-0017cece-4fa8-11e8-9d37-9ca7c3d9bea1.png)

You'll see sample indexes defined in `datastore-indexes.xml`.
![selection_012](https://user-images.githubusercontent.com/10523105/39646009-078cce20-4fa8-11e8-83f7-5f39678603d6.png)

Look into the sample project (perhaps mostly `pom.xml`) and compare it with your project.

**Comment by jfinci1** [comment]
@chanseokoh 

> google-cloud-bom

thanks for the response.  the project you've posted looks to be a pom which includes every gcloud dependency.. I certainly don't need all of those.   

are you able to specifically point out what I might require for this to work? 

the versions you've included here are snapshots as well which means they aren't really comparable..

> <datastore.version>1.28.1-SNAPSHOT</datastore.version>
> 0.46.1-alpha-SNAPSHOT

**Comment by chanseokoh** [comment]
> google-cloud-bom
>
> the project you've posted looks to be a pom which includes every gcloud dependency.. I certainly don't need all of those.

BTW, the BOM doesn't pull in any dependencies. It just lets you free from managing versions of some dependencies only when you opt to pull in them. You can learn more about BOM from, e.g., https://hackernoon.com/maven-bill-of-materials-dependency-b6eb88f5c188

**Comment by jfinci1** [comment]
Thanks for your continued support here.

I do see these now in the local admin console. However, queries are still giving errors- I was under the impression these indexes would be auto generated?

**Comment by loosebazooka** [comment]
Have you enabled auto index generation in your datastore indexes file?

On the root tag, add the atrribute:
```
<datastore-indexes
  autoGenerate="true">

```

**Comment by jfinci1** [comment]
Yes, I have, here is my datastore-indexes.xml

`<datastore-indexes
    autoGenerate="true">
  <datastore-index kind="SyncJob">
    <property name="merchant_id"/>
    <property name="sync_type"/>
    <property name="sync_start_time" direction="desc"/>
  </datastore-index>
  <datastore-index kind="SyncJob">
    <property name="merchant_id"/>
    <property name="sync_start_time" direction="desc"/>
  </datastore-index>
</datastore-indexes>`

**Comment by jfinci1** [comment]
also, i noticed that it seems to be writing data to both a remote app engine datastore and to the local_db.bin and which is reporting lack of indexes is unclear to me.

**Comment by jfinci1** [comment]
![image](https://user-images.githubusercontent.com/5992006/39657003-e55397c4-4fb8-11e8-87bf-7272de08711e.png)

According to this documentation (https://cloud.google.com/appengine/docs/standard/java/config/indexref) indexes defined in XML without a direction default to asc.

I can confirm, though, that this is not the case.  They default to desc as well, at least from the _ah/admin/datastore screen

**Comment by chanseokoh** [comment]
I *think* the gcould Datastore emulator is a separate thing and independent from the Datastore backed by the local dev app server. I guess your app is mixing the two and talking to two separate stores.

https://cloud.google.com/appengine/docs/standard/java/config/indexconfig doesn't say anything remotedly related to the gcloud emulator.

However, I know nothing about the gcloud emulator honestly, and I could be totally wrong. Other folks could confirm.

**Comment by chanseokoh** [comment]
These may help you understand https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/304#issuecomment-386758877:

https://cloud.google.com/appengine/docs/standard/python/tools/using-local-server#using_the_local_datastore
https://cloud.google.com/datastore/docs/tools/datastore-emulator#emulator_data_directories
