### ISSUE TITLE
Read project deployment config from all sources.

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/app-maven-plugin#305]
Introduces some keyworks for 'project' that allow the user to configure what they want as their source of truth during deployment

Allow project/version config to be read from

1. pom.xml (this is default)
2. appengine-web.xml : `<project>APPENGINE_CONFIG</project>`
3. gcloud global state: `<project>'GCLOUD_CONFIG'</project>`

`APPENGINE_CONFIG`/`GCLOUD_CONFIG` are not valid google cloud project
names and are reconfigured by the plugin.

Flexible projects do not allow the user to configure `APPENGINE_CONFIG`

**Comment by TadCordle** [comment]
Fixed with #307
