### ISSUE TITLE
Allow running AppEngine for another project using devserver.services

### ISSUE THREAD

**Issue by matt-blanchette** [GoogleCloudPlatform/app-maven-plugin#312]
The previous Maven plugin for AppEngine had a configuration property "appDir" 
to allow deploying another project.

The current plugin only allows deploying the current Maven project 
and will fail when the `WEB-INF/appengine-web.xml` is not found: 
`Dev App Server does not support App Engine Flexible Environment applications.`

It appears the property `devserver.services` should allow the same functionality,
if it was used in RunMojo.isStandardEnvironmentApp()

**Comment by matt-blanchette** [comment]
I've tested this fix in RunMojo:
> protected boolean isStandardEnvironmentApp() {
      return new File(services.get(0), "/WEB-INF/appengine-web.xml").exists();
  }

The RunMojoTest would need `src/main/appengine` changed to a valid standard env path like `src/test/resources/projects/standard-project/src/main/webapp`

**Comment by matt-blanchette** [comment]
Added pull request #313

**Comment by loosebazooka** [comment]
Can you explain how you are using this? Is this is a workaround for using a parent pom with multiple modules?

**Comment by matt-blanchette** [comment]
We have a separate UI automation project to deploy the main application using start/stop goals as integration test.

**Comment by matt-blanchette** [comment]
This can be closed, now that #313 was merged
