### ISSUE TITLE
error when having a Cloud SDK with serverless EA commands

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/app-maven-plugin#314]
I installed a serverless beta(or ea) component in the cloud SDK....

Now, the GAE Maven plugin does not work anymore with this error at deployment time:
Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3.2:deploy (default-cli) on project xxxx : Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.3.2:deploy failed: Pattern found in the Cloud SDK version file could not be parsed: HEAD: Pattern "HEAD" is not a valid CloudSdkVersion. -> [Help 1]

**Comment by chanseokoh** [comment]
Looks like the Cloud SDK you (and the tool) are using is not an official release. Happens with a dogfood version, for example. I believe `gcloud version` would show its version as `HEAD`.

**Comment by chanseokoh** [comment]
@appu I vaguely remember you did something in this case, e.g., to give a better error message? Can't remember exactly though.

**Comment by chanseokoh** [comment]
@loosebazooka

**Comment by patflynn** [comment]
We should definitely not fail in this scenario.

**Comment by chanseokoh** [comment]
https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/561

**Comment by chanseokoh** [comment]
Dup of #561 and fixed by #670. Closing.
