### ISSUE TITLE
Failure when using non-default named yaml file

### ISSUE THREAD

**Issue by gjferrier** [GoogleCloudPlatform/app-maven-plugin#316]
Hi,

I've ran into a problem where specifying a non-default yaml file, e.g. mynew-app.yaml, the deployment fails.  Here's the console output for the failed attempt

INFO: submitting command: /usr/lib/google-cloud-sdk/bin/gcloud app deploy /var/lib/jenkins/workspace/test-deploy/src/main/appengine/test-deploy-app.yaml

The deploy fails with 

[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Your application does not satisfy all of the requirements for a runtime of type [java].  Please correct the errors and try again.

However, if I use the same file, but use the default name 'app.yaml' the deployment works fine.

I am using version 1.3.1.

**Comment by chanseokoh** [comment]
Dup of #211. (However, the info in #211 may be out of date.) Closing.
