### ISSUE TITLE
Plugin doesn't respect port configuration for secondary services

### ISSUE THREAD

**Issue by mayorchyk** [GoogleCloudPlatform/app-maven-plugin#330]
Plugin doesn't pick up ``deploy.port`` value from configuration for secondary service when multi service application is launched on local host. A new port values is assigned on every application launch.

**Example.**
Parent pom.xml contains:
```
<modules>
  <module>core</module>
  <module>reports</module>
</modules>

<build>
  <plugins>
    <plugin>
      <groupId>com.google.cloud.tools</groupId>
      <artifactId>appengine-maven-plugin</artifactId>
      <version>2.0.0-rc1</version>
    </plugin>
  </plugins>
</build>
```
app-engine-plugin in core module configured as the following:
```
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>appengine-maven-plugin</artifactId>
    <configuration>
    <deploy.project>${app.deploy.project}</deploy.project>
    <deploy.version>${app.deploy.version}</deploy.version>
    <services>
      <!-- default service -->
      <service>${project.build.directory}/${project.name}-${project.version}</service>
      <!-- One for each additional service -->
      <service>${project.parent.basedir}/reports/target/reports-${project.version}</service>
    </services>
    <promote>false</promote>
    <enableJarClasses>true</enableJarClasses>
    <enableJarSplitting>true</enableJarSplitting>
    <deleteJsps>true</deleteJsps>
    <address>0.0.0.0</address>
    <port>8888</port>
    <adminPort>8080</adminPort>
    <jvmFlags>
           ...
    </jvmFlags>
  </configuration>
</plugin>
```
app-engine-plugin in core module configured as the following:
```
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>appengine-maven-plugin</artifactId>
  <configuration>
    <deploy.project>${app.deploy.project}</deploy.project>
    <deploy.version>${app.deploy.version}</deploy.version>
    <deploy.service>snapengage-reports</deploy.service>
    <promote>false</promote>
    <enableJarClasses>true</enableJarClasses>
    <enableJarSplitting>true</enableJarSplitting>
    <deleteJsps>true</deleteJsps>
    <port>8889</port>
    <jvmFlags>
      ...
    </jvmFlags>
  </configuration>
</plugin>
```

When application is launched reports service is deployed on a random port, although 8889 was specified in configuration.

**Comment by loosebazooka** [comment]
That is right, the multimodule implementation of the dev_appserver doesn't read that port. Is there a reason why you need to know the port number for secondary services? Inter-service communication can be done via the modules api (https://cloud.google.com/appengine/docs/standard/java/using-the-modules-api).

**Comment by mayorchyk** [comment]
In my case ``reports`` module contains a collection of JSPs:
```
localhost:{port}/reports/report1.jsp
localhost:{port}/reports/report2.jsp
```
To access a report I have to provide port number. Each time a different one.
I would like to have a fixed port number, or make it possible to access reports JSPs from the default module.

**Comment by loosebazooka** [comment]
Right, so you can use the modules api (from [com.google.appengine:appengine-api-1.0-sdk:1.9.64](https://search.maven.org/artifact/com.google.appengine/appengine-api-1.0-sdk/1.9.64/jar))

```
    ModulesService modulesService = ModulesServiceFactory.getModulesService();
    for (String module : modulesService.getModules()) {
      String modulePath = modulesService.getVersionHostname(module, "no_version"));
      String jspPath = modulePath + "/reports/report.jsp"
    }
```
or something. "no_version" is the version in the devappserver for modules.

**Comment by mayorchyk** [comment]
Thanks for clarification.

**Comment by chanseokoh** [comment]
I wonder if this workaround is effective for assigning static ports: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/235#issuecomment-356014144
