### ISSUE TITLE
Expose new cloud SDK flag   --flags_file

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/app-maven-plugin#340]
See 
Release notes can be found here:
https://cloud.google.com/sdk/docs/release-notes

 ## 225.0.0 (2018-11-13)

### Cloud SDK

* Added the `--flags-file`=_YAML-FILE_ flag, available to all gcloud commands,
  for specifying complex flag values in any command interpreter. See
  `gcloud topic flags-file` for more information.

A Java user should be able to configure the new --flags_file file from Maven (and Gradle).

**Comment by JoeWang1127** [comment]
close as not planned
