### ISSUE TITLE
Consider renaming to `appengine-maven-plugin` and bump major version

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/app-maven-plugin#35]
Following on [the discussion from the use of `app` vs `appengine`](https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/pull/105#discussion_r65966045) in GoogleCloudPlatform/app-tools-lib-for-java, the use of `app` in this plugin name is confusing.

Since this plugin is to replace the older `appengine-maven-plugin`, can't it be called `appengine-maven-plugin` and bump the major version to 2.x?  Although the version bump isn't strictly necessary since this plugin is in a different group (`com.google.cloud.tools` vs `com.google.appengine` for the older plugin), it provides a subtle clue that it's the successor.

cc @elharo

**Comment by meltsufin** [comment]
It's a reasonable argument, but renaming would apply more broadly to app-gradle-plugin and the common library as well.
@patflynn @loosebazooka

**Comment by patflynn** [comment]
Let's discuss offline. Brian can you start a thread?

**Comment by meltsufin** [comment]
Resolved by #42
