### ISSUE TITLE
new use case for microprofile apps support and appengine

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/app-maven-plugin#357]
Playing with Helidon microprofile and the new GAE runtime...

See https://github.com/oracle/helidon/tree/master/examples/quickstarts/helidon-quickstart-mp
the build steps:
- create a target/libs directory with all the dependent jars
- the main jar with correct manifest describing a main class and the classpath with all the libs/* jars

`Class-Path: libs/helidon-microprofile-1.2-0.11.0-SNAPSHOT.jar libs/helid
 on-microprofile-1.1-0.11.0-SNAPSHOT.jar libs/helidon-microprofile-serve
 r-0.11.0-SNAPSHOT.jar libs/weld-se-core-3.0.3.Final.jar libs/weld-envir
 onment-common-3.0.3.Final.jar libs/weld-core-impl-3.0.3.Final.jar libs/
etc,etc
`

Now, with version 2 rc of the Maven plugin, ideally, we should be able to copy the directory libs/ in the staging directory, but we cannot. If I use this plugin configuration:

````
     <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>2.0.0-rc4</version>
        <configuration>
          <extraFilesDirectory>${copied.libs.dir}</extraFilesDirectory>
        </configuration>
      </plugin>

````
I see in appengine-stage directory the correct main jars, but all the libs/*.jars at the same level, so not under the libs/ directory...

Could we add a way to copy with keeping the directory name?

**Comment by patflynn** [comment]
Could we inspect the manifest classpath and include any jar entries
automatically?

**Comment by chanseokoh** [comment]
> create a target/libs directory with all the dependent jars

I think the usage should be to put the JARs under `target/any-extra-files-I-want/libs` and set `<extraFilesDirectory>.../target/any-extra-files-I-want</extraFilesDirectory>`.

**Comment by ludoch** [comment]
I like Patrick's option, but we also need to be flexible like a copy commands with wildcards and dir management imo

**Comment by ludoch** [comment]
````
          <extraFilesDirectory>${copied.libs.dir}</extraFilesDirectory>
````
could copy with the dir name
and 
````
          <extraFilesDirectory>${copied.libs.dir}/*.jar</extraFilesDirectory>
````
could copy just the jars?

**Comment by chanseokoh** [comment]
Maybe we could extend the contract so that, with

```
foo/
+-- bar/
    +-- baz/
```

- `<extraFilesDirectory>/foo/bar/<extraFilesDirectory>` results in `baz` in the staging directory. (This behavior of copying the contents is the current contract.)
- `<extraFilesDirectory>/foo/bar<extraFilesDirectory>` results in `bar` (hence `bar/baz` too) in the staging directory.

**Comment by loosebazooka** [comment]
FYI(`@HEAD`): `ExtraFilesDirectory` is now `ExtraFilesDirectories` and is a List.
I hesitate to add extra logic/convention into this beyond keeping it a simple copy.

As for wildcards, pattern matching, etc, the build systems already have copy mechanisms ([`CopyTask`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html) in gradle and [`Copy Resources`](https://maven.apache.org/plugins/maven-resources-plugin/examples/copy-resources.html) in maven) that implement this and we can help the user make use of those mechanisms.

**Comment by ludoch** [comment]
Personally, I like the bar and bar/ proposal. Similar to cp command?

**Comment by loosebazooka** [comment]
I see. Maven does make it harder since you cannot inject tasks everywhere.
You would probably have an intermediate step that does that.
maven-resources-plugin outputs to some directory 'xyz' -> `filtered-xyz'
that directory is defined in the extraFilesDirectories = 'filtered-xyz'

**Comment by ludoch** [comment]
Complicated... What about simple UX?

**Comment by loosebazooka** [comment]
Well adding more options doesn't necessarily provide a simpler UX, it just complicates the config for simple users, and I would argue for the simplest contract as the best solution. Building in assumptions and conventions is usually confusing and harder to debug.

In the case that the user wants to do advanced things, I would make the case that they are willing to go through the extra effort to configure that advanced filtering.

**Comment by ludoch** [comment]
This example (helidon) shows a std pattern: fatjar depending on depedent jars under lib/
You are asking to to something extra for App Engine which is a double copy of jars... Not pretty at all for a well known pattern.

**Comment by ludoch** [comment]
(Triple copy with staging)

**Comment by loosebazooka** [comment]
It seems like a solution is to stop deleting the staging directory during deployment. This would allow us to re-use the mechanism provided by copy-resources, copy-dependencies, etc to copy them directly into the appengine directory?

**Comment by saturnism** [comment]
Since we know the target is already a JAR, can we simply extract the final JAR into staging and upload that? This would work for a number of different plugins, and pattern can work w/ Gradle too.

**Comment by patflynn** [comment]
What if we just gave up on making of hacking this interface for java 11 jar
support and used jib to build an appengine 11 based runtime container on
the client side and deploy that?

**Comment by loosebazooka** [comment]
https://github.com/GoogleCloudPlatform/app-maven-plugin/pull/361

**Comment by saturnism** [comment]
> What if we just gave up on making of hacking this interface for java 11 jar support and used jib to build an appengine 11 based runtime container on the client side and deploy that?

interesting. sounds very cool if it works seamlessly. this might resolve quite a few issues.

**Comment by loosebazooka** [comment]
@ludoch this should be possible now with rc5.

Just configure the copy-dependencies goal/plugin to write those files into: `${project.build.directory}/appengine-staging`

**Comment by ludoch** [comment]
Testing now. Thanks!

**Comment by ludoch** [comment]
Love it!
