### ISSUE TITLE
appengine:run mangles jvmFlags properties that contain comma

### ISSUE THREAD

**Issue by BenWhitehead** [GoogleCloudPlatform/app-maven-plugin#365]
### Bug
I discovered this bug while attempting to setup remote debugging and received an error when 
trying to pass the jvm args for jdwp. The value I set for `jvmFlags`
```xml
<jvmFlags>-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n</jvmFlags>
```

When I attempt to run the following error is logged to stderr:
```
[INFO] --- appengine-maven-plugin:1.3.2:run (default-cli) @ appengine-maven-plugin-bug ---
Jan 16, 2019 3:44:59 PM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: ${JAVA_8_HOME}/jre/bin/java -agentlib:jdwp=transport=dt_socket address=8000 server=y suspend=n -Duse_jetty9_runtime=true -D--enable_all_permissions=true -Dappengine.sdk.root=${GCLOUD_SDK_HOME}/platform/google_appengine/google/appengine/tools/java -cp ${GCLOUD_SDK_HOME}/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com.google.appengine.tools.development.DevAppServerMain --allow_remote_shutdown --disable_update_check --no_java_agent ${PROJECT_ROOT}/target/appengine-maven-plugin-bug-0.1.0-SNAPSHOT
[INFO] GCLOUD: ERROR: JDWP Non-server transport dt_socket must have a connection address specified through the 'address=' option
[INFO] GCLOUD: ERROR: JDWP invalid option: -agentlib:jdwp=transport=dt_socket
```

Notice the argument passed to the jvm is in fact the following (notice the missing commas)
```
-agentlib:jdwp=transport=dt_socket address=8000 server=y suspend=n
```
The [documentation](https://cloud.google.com/appengine/docs/standard/java/tools/maven-reference#appenginerun) does not not a possible way to escape the commas or prevent this from happening.

### Reproduction
I've created a minimized project to illustrate and provide a reproduction [here](https://github.com/BenWhitehead/appengine-maven-plugin-bug)

### My Environment
* Linux 64-bit debian based, 4.18.10
* Oracle Java 1.8u191
* Maven 3.6.0
* `com.google.cloud.tools:appengine-maven-plugin:1.3.2`

**Comment by BenWhitehead** [comment]
When I slip it out to the individual value it no longer mangles the arg.

Is there any way the docs at https://cloud.google.com/appengine/docs/standard/java/tools/maven-reference#appenginerun could be updated to explicitly show that `<jvmFlags>` is a list?

**Comment by loosebazooka** [comment]
Yeah, will file something with our docs team.

**Comment by loosebazooka** [comment]
fixed
