### ISSUE TITLE
Show error message for supported JDK

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/app-maven-plugin#367]
A stackoverflow user reported NoSuchMethodException when the person used IBM JDK to follow [Appengine Standard Hello World Java8](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/helloworld)

https://stackoverflow.com/questions/54383402/local-google-cloud-appengine-not-starting (The user resolved the issue by himself)

An error message on supported JDK is helpful for users.

**Comment by loosebazooka** [comment]
unfortunately this is not something we can handle at our level, the call comes from the appengine sdk. Closing as "not-feasible"
