### ISSUE TITLE
Stages App Engine Standard Environment - when app.yaml says "env: flex"

### ISSUE THREAD

**Issue by nealeu** [GoogleCloudPlatform/app-maven-plugin#373]
I'm trying out Google Cloud, and it seems that whatever I do, I am getting "Detected App Engine standard environment" when I run appengine:stage or deploy.

So, I've checked out this plugin project and a search is showing up that I should be seeing that it has detected an app.yaml or appengine-web.xml based project.

I can't find anywhere in the code where "Detected App Engine standard environment" (or flexible) is output, only that it is in the tests.

How do I get it to see my app.yaml?

**Comment by nealeu** [comment]
Update: I see from the project history that lots is happening for 2.0.0 release, so looking back at the code (I really shouldn't have to do this!), I can find the text relating to standard environment.

And... It appears that having renamed appengine-web.xml to appengine-web.xml.dont-use, this was being detected as present (Path.resolve() matching on prefix?).

Anyway.  This looks informational but worth a quick comment relating to v2.0.0 and perhaps a test to ensure that people don't get caught the way I did.  It's taken several hours to work through :)

**Comment by chanseokoh** [comment]
Hi @nealeu, thanks for updating what's going on. I'll take a look why it picks up `appengine-web.xml.dont-use`.

And just for those who are not aware, we have a lot of release candidates, and we've made a lot of design changes between them.

`2.0.0-rc1`
`2.0.0-rc2`
`2.0.0-rc3`
`2.0.0-rc4`
`2.0.0-rc5`

**Comment by chanseokoh** [comment]
[`isAppEngineWebXmlBased()`](https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/v2.0.0-rc5/src/main/java/com/google/cloud/tools/maven/stage/AbstractStageMojo.java#L177) checks if `target/<finalName>/WEB-INF/appengine-web.xml` exists. ([The source directory for staging is the exploded WAR directory.](https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/v2.0.0-rc5/src/main/java/com/google/cloud/tools/maven/stage/AbstractStageMojo.java#L67)) I think your build directory had `appengine-web.xml` hanging around. If you do `mvn clean`, I bet you will be able to have `appengine-web.xml.dont-use` again.

**Comment by nealeu** [comment]
Hi @chanseokoh.

It seems that you were right.  I've got too used to not needing to do mvn clean locally :)
