### ISSUE TITLE
gcloud beta app deploy

### ISSUE THREAD

**Issue by spyrosel** [GoogleCloudPlatform/app-maven-plugin#374]
I can't find a way to make it run "gcloud beta app deploy" instead of "gcloud app deploy" when running "appengine:deploy". Is there any? I want to use "network: session_affinity: true" and it seems that using "gcloud beta app deploy" is the only way to do it.

**Comment by chanseokoh** [comment]
I assume you're working on the App Engine flexible environment. From what I see [here](https://cloud.google.com/appengine/docs/flexible/java/using-websockets-and-session-affinity), it doesn't say it requires `gcloud beta app deploy` to enable session affinity. Does `gcloud app deploy` complain when you have `session_affinity: true`?

**Comment by spyrosel** [comment]
Yes I'm working on the flexible environment. It doesn't complain but it doesn't work either. I have asked a question in stackoverflow [here](https://stackoverflow.com/questions/54809725/does-google-app-engine-support-session-affinity-in-the-java-flexible-environment) and a user replied saying that using "gcloud beta app deploy" will make it work.

**Comment by loosebazooka** [comment]
yeah to use beta currently you must do something like
```
$ mvn package appengine:stage
$ gcloud beta app deploy ./target/appengine-staging/app.yaml
```

**Comment by loosebazooka** [comment]
@spyrosel this should be available now with the `gcloudMode` configuration option.
