### ISSUE TITLE
Missing "skip" configuration for deploy mojo

### ISSUE THREAD

**Issue by theHilikus** [GoogleCloudPlatform/app-maven-plugin#377]
It is common practice for maven plugins to implement a "skip" setting to disable execution of a mojo in particular submodules. The usecase is usually that you have a multimodule project with many submodules and most of them need to run the plugin; so instead of declaring the plugin as `managedPlugin` in the parent and then as a plugin in every child, you declare it as a regular `plugin` in the parent and disable it in the submodules that should not run it

My particular usecase is very similar. Most of my submodules are appengine services but there's a `common` module of java classes (with `<packaging>jar</packaging>`) used by all my services. When the appengine-maven-plugin tries to deploy that common module, it fails

```
[INFO] --- appengine-maven-plugin:2.0.0-rc5:deploy (default-cli) @ backend-common ---
[INFO] Staging the application to: /home/hilikus/git/backend/services/backend-common/target/appengine-staging
[INFO] Detected App Engine app.yaml based application.
...
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.200 s
[INFO] Finished at: 2019-03-31T16:17:32-04:00
[INFO] Final Memory: 54M/444M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:2.0.0-rc5:deploy (default-cli) on project backend-common: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:2.0.0-rc5:deploy failed: com.google.cloud.tools.appengine.AppEngineException: java.nio.file.NoSuchFileException: /home/hilikus/git/backend/services/backend-common/src/main/appengine/app.yaml -> [Help 1]
```
Is there any mechanism that I missed to avoid this problem? if not, it would be a nice to have

**Comment by loosebazooka** [comment]
Couldn't you just create a intermediate parent for the appengine modules? Declaring something just to disable it seems like a weird anti pattern.

**Comment by theHilikus** [comment]
@loosebazooka there are a lot of workarounds available (including the one you suggested) but they are all dirtier than a skip flag. You can see some in this answer https://stackoverflow.com/a/7821446/1086540

here are some *official* maven plugins that have the skip flag, proving (to me at least) that it's not really an antipattern
http://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#skip
https://maven.apache.org/components/plugins/maven-compiler-plugin/compile-mojo.html#skipMain
https://maven.apache.org/plugins/maven-resources-plugin/resources-mojo.html#skip
https://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-mojo.html#skip

**Comment by loosebazooka** [comment]
Yeah, so those examples make some sense for goals:
1. That are bound to the default build lifecycle (some even recommend *against* using them) where generally a user doesn't have much control over their inclusion.
2. Where you could conditionally skip (tests, checkstyle) when someone might temporarily want to ignore something they've configured to regularly run for faster development.

I just don't see us implementing this. Perhaps it's subjective, but I do not think an extra parent pom is a hack if you're already trying to use parent pom inheritance for configuration.

**Comment by theHilikus** [comment]
ok. I understand
Thank you for your input anyway :)

**Comment by theHilikus** [comment]
that's great. i will allow me (and probably others) to deploy multiple services in one shot

**Comment by loosebazooka** [comment]
fixed by #379

**Comment by loosebazooka** [comment]
will probably be out in 2.0.0-rc6

**Comment by loosebazooka** [comment]
`2.0.0-rc6` has been released with this fix.
