### ISSUE TITLE
deploy should deploy app.yaml, index.yaml, cron.yaml, and dos.yaml

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-maven-plugin#39]
Based off of the AppCfg code [here](https://code.google.com/p/googleappengine/source/browse/trunk/java/src/main/com/google/appengine/tools/admin/AppVersionUpload.java?r=182#152), I think we should deploy all of the above-mentioned configs at deploy time by default.

**Comment by meltsufin** [comment]
Closing because we decided not to do this.
