### ISSUE TITLE
 Failed to run devappserver: No appengine-web.xml file exception

### ISSUE THREAD

**Issue by pavankjadda** [GoogleCloudPlatform/app-maven-plugin#390]
I upgraded gcloud tools to the latest version and trying to execute my project. The updated plugin looks like below
```
<plugin>
    <groupId>com.google.cloud.tools</groupId>
     <artifactId>appengine-maven-plugin</artifactId>
     <version>${appengine-maven-plugin.version}</version>
      <configuration>
          <projectId>${gcloud-projectId}</projectId>
           <version>1</version>
       </configuration>
 </plugin>
```
When I run my project with the command `$  mvn com.google.cloud.tools:appengine-maven-plugin:run`, I get the following error
```
Failed to run devappserver: java.nio.file.NoSuchFileException: /Users/pjadda/IdeaProjects/JobBoard/backend/target/backend-0.0.2-SNAPSHOT/WEB-INF/appengine-web.xml
```

I think a new plugin is not copying my **appengine-web.xml** file to target jar file

**Comment by loosebazooka** [comment]
Looks like you need to run `package` first to build the application. (this requirement is new in 2.0.0)

`mvn package appengine-maven-plugin:run`

**Comment by pavankjadda** [comment]
@loosebazooka I still get the same error despite when I run 
` $ mvn package com.google.cloud.tools:appengine-maven-plugin:run -DskipTests`

**Comment by loosebazooka** [comment]
I'm super confused, this is unexpected. Can you provide us with a sample project that shows this or at least at minimum your `pom.xml` and your directory/file structure? I would assume something about your configuration is modifying the final artifact incompatibly with standard war builds? app-maven-plugin doesn't do the war build. So if you're producing the correct war, I would expect it to not work.

**Comment by loosebazooka** [comment]
@pavankjadda Any update here?

**Comment by pavankjadda** [comment]
@loosebazooka I sent you an invite to my Github repository. Please have a look

**Comment by chanseokoh** [comment]
I'd like to see the contents of the WAR build directory after `mvn package`. Could you do the following?

1. Close your IDE (just to be safe, because IDE can interfere builds).
1. Open a new terminal. `cd` into the root project.
1. `mvn clean`
1. `mvn package`
1. `tree backend/target/backend-0.0.2-SNAPSHOT`
1. `tree backend/target/backend-0.0.2-SNAPSHOT/WEB-INF`

**Comment by loosebazooka** [comment]
looks like you need to specify `war` packaging in your backend so maven treats it like a war... without it, it will be packaged like a jar and things will not work as expected. Please take a look at the maven docs: https://maven.apache.org/plugins/maven-war-plugin/usage.html

**Comment by pavankjadda** [comment]
@chanseokoh I do not have `backend/target/backend-0.0.2-SNAPSHOT` directory. I see only `backend-0.0.2-SNAPSHOT.jar` and `backend-0.0.2-SNAPSHOT.jar.original` on backend/target folder

When I execute the requested commands, I see the following error
```
$ tree backend/target/backend-0.0.2-SNAPSHOT.jar
backend/target/backend-0.0.2-SNAPSHOT.jar [error opening dir]

0 directories, 0 files
```

So, I extracted the jar file and I see following files

![Screen Shot 2019-06-11 at 4 25 07 PM](https://user-images.githubusercontent.com/17564080/59304186-bc490b80-8c65-11e9-83c0-2055d549e9e7.png)

**Comment by pavankjadda** [comment]
> looks like you need to specify `war` packaging in your backend so maven treats it like a war... without it, it will be packaged like a jar and things will not work as expected. Please take a look at the maven docs: https://maven.apache.org/plugins/maven-war-plugin/usage.html

Should I do this? Because I am able to deploy the appl to gCloud and it's running without any issues
https://job-board-228920.appspot.com/

**Comment by loosebazooka** [comment]
Hrmm... so it wasn't clear what you wanted to do before this, but I now I seem to understand. You're deploying a non-war, and it's being treated that way (which makes sense). We _do not_ support `appengine:run` for non-war projects (and perhaps the error message could be better), because the devappserver is designed for appengine-standard-java8-war projects. If you want to run it locally, you can invoke the springboot runner directly?

**Comment by loosebazooka** [comment]
I may have jumped to a few conclusions. Do you want to run a war or a jar?

**Comment by pavankjadda** [comment]
> I may have jumped to a few conclusions. Do you want to run a war or a jar?

I didn't know AppEngine does not support JAR files. By the way, Is this mentioned in AppEngine docs? if yes, I might have overlooked it. So, when I run `mvn appengine:deploy`, the application is deployed as WAR file. Quick question, where can I find the deployed application on AppEngine instance (path to war file)?

**Comment by loosebazooka** [comment]
Are you using the flex runtime, do you have an app.yaml somewhere?

**Comment by pavankjadda** [comment]
Yes. I do have app.yaml file in my environment

**Comment by loosebazooka** [comment]
Okay yeah, so there's actually two workflows:
1. appengine-web.xml workflow for `war` projects (which allows `appengine:run`)
2. app.yaml workflow for all other projects <-- where your project falls under.

So really you are not going to be able to use `appengine:run` for local testing, and I should update the error message for that.

**Comment by pavankjadda** [comment]
Okay. I am closing the issue as I can not use `appengine:run` for my app.

**Comment by lvalladares** [comment]
Hello

This means that if i have an app with app.yaml workflow (Java 11 apps) i can not test it on local? Each change i made will need a new deploy to the cloud? This is a permanent decision or it will be eventually released? If its permanent what is the recomended workflow for development in this case? How can we simulate all the Google services previously included in dev appserver (Storage, Datastore...)?

Thanks

**Comment by loosebazooka** [comment]
As far as I know, those services are only accessible via the appengine-specific apis in the devappserver.

I think you're going to have to run the service specific emulator... but let me find out: @saturnism @ludoch @eamonnmcmanus ?

**Comment by khoek** [comment]
Any news on this? It seems like a terrible situation... :(

**Comment by jpswain** [comment]
This worked for me:
```
mvn package appengine:run
```

**Comment by saturnism** [comment]
In the App Engine Java 11 runtime (w/ JAR), the App Engine specific APIs are replaced by the standard GCP service APIs.

https://cloud.google.com/appengine/docs/standard/java11/java-differences#app-engine-api-migration

Some services have emulators that you can test locally with (`gcloud beta emulators`).

**Comment by BrendonIwata** [comment]
@saturnism oh man thanks a lot, i'm was giving up! you saved my day :-)
