### ISSUE TITLE
Set an env variable to track server-side usage of gcloud

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/app-maven-plugin#4]
The same thing as in [here](https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/3).

**Comment by meltsufin** [comment]
@chanseokoh has it been settled what we're actually passing in for CLOUDSDK_METRICS_ENVIRONMENT and CLOUDSDK_METRICS_ENVIRONMENT_VERSION?

**Comment by chanseokoh** [comment]
For IntelliJ, we pass `gcloud-intellij`. For others, you may suggest and use something similar along the line. For VERSION, let's pass the version of the plugins. For IntelliJ, it would probably be like `0.9.5-beta`.
