### ISSUE TITLE
doc: clarify how this project relates to gcloud-maven-plugin

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/app-maven-plugin#40]
https://github.com/GoogleCloudPlatform/gcloud-maven-plugin

**Comment by meltsufin** [comment]
@arouzrokh

**Comment by joaoandremartins** [comment]
This project will deprecate the previous mvn appengine and gcloud plugins. This one will maintain the "appengine" name, to make it more or less seamless for users to upgrade.

**Comment by patflynn** [comment]
@loosebazooka Can you update the README to fix this?

**Comment by akerekes** [comment]
glcoud-maven-plugin has been deprecated in favor of this plugin.
