### ISSUE TITLE
Springboot thin jars?

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/app-maven-plugin#408]
Mirror of https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/367 for maven

A proposed way to do this in maven is to build a thin-jar using maven with correct classpath + copy dependencies on build:

```xml
<!-- configure jar plugin correctly -->
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-jar-plugin</artifactId>
  <configuration>
    <archive>
      <manifest>
        <addClasspath>true</addClasspath>
        <classpathPrefix>lib/</classpathPrefix>
        <mainClass>fully.qualified.MainClass</mainClass>
      </manifest>
    </archive>
  </configuration>
</plugin>
<!-- configure copy dependencies over to target/lib -->
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-dependency-plugin</artifactId>
  <version>3.1.1</version>
  <executions>
    <execution>
      <id>copy-dependencies</id>
      <phase>prepare-package</phase>
      <goals>
        <goal>copy-dependencies</goal>
      </goals>
      <configuration>
        <outputDirectory>${project.build.directory}/lib</outputDirectory>
        <overWriteReleases>false</overWriteReleases>
        <overWriteSnapshots>false</overWriteSnapshots>
        <overWriteIfNewer>true</overWriteIfNewer>
      </configuration>
    </execution>
  </executions>
</plugin>
```

and then to explicitly disable the boot repackaging mechanism using the property:
```xml
<properties>
  ...
  <spring-boot.repackage.skip>true</spring-boot.repackage.skip>
</properties>
```
so now when you do:
```
./mvnw package appengine:stage
```
you should see a correctly configured appengine staging directory in `target`

**Comment by loosebazooka** [comment]
It important to note here that springboot does A LOT of configuration in there parent. Which is why this seems like a lot of configuration in comparison. Since we don't have the opportunity to replace the parent for springboot projects, this kind of manual config might be necessary.

**Comment by saturnism** [comment]
actually, Spring Boot can create a Thin Jar using Thin Wrapper: 
https://github.com/ludoch/samples/blob/master/java11/springboot-thin/pom.xml

**Comment by loosebazooka** [comment]
Oh so this isn't really necessary?

**Comment by saturnism** [comment]
right.. otherwise i'll attempt to download all the dependencies :(

**Comment by loosebazooka** [comment]
Seems weird that spring boot people wont just use the standard java packaging features.
