### ISSUE TITLE
appengine:cloudSdkLogin will repeatedly hang once you close your browser

### ISSUE THREAD

**Issue by inovikov-gamajun** [GoogleCloudPlatform/app-maven-plugin#412]
v2.2.0 (Windows 10 64-bit)

Hello. I have run into the following issue:
1) Run `mvn appengine:cloudSdkLogin` in the command line.
2) When Google sign-in browser window is open close it instead of signing-in.
3) Terminate the command in the command line (as it will not finish itself).
4) Run `mvn appengine:cloudSdkLogin` again.
5) When Google sign-in window is open sign-in properly.

Observed result: `appengine:cloudSdkLogin` will hang after the prompt "Your browser has been opened to visit: [https://accounts.google.com/o/oauth2/auth...]". Terminating the command and retrying will not help. So making this mistake once will block you forever.

Found workaround (this might give you a clue). To fix the issue you need to run these two Google Cloud SDK commands in this order (make sure they finish properly):

1. `gcloud auth login --no-launch-browser`
2. `gcloud auth login`

What makes me think it is app-maven-plugin bug is that from what I see in the plugin output `cloudSdkLogin` is internally using `gcloud auth login`, but the latter functions normally after you close Google sign-in window and run it again.

**Comment by loosebazooka** [comment]
Weird, okay we'll take a look. Open to contributions too.

**Comment by emmileaf** [comment]
Closing given age of this issue and that a workaround exists - please re-open if still relevant.
