### ISSUE TITLE
pass --verbose parameters to appengine process

### ISSUE THREAD

**Issue by rmacd** [GoogleCloudPlatform/app-maven-plugin#415]
May be being an idiot here, but it looks like it's impossible to pass through --verbose= parameter through to appengine process.

Have attempted both the following, to no avail:

```
<additionalArguments>
    <additionalArgument>--verbose=debug</additionalArgument>
</additionalArguments>
...
<jvmFlags>
    <jvmFlag>--verbose=debug</jvmFlag>
</jvmFlags>
```

**Comment by loosebazooka** [comment]
Hrmm... can you point to docs about this verbose flag. I'm not sure which one you're talking about.

**Comment by zhumin8** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
