### ISSUE TITLE
Cloud Build step suddenly failing to build image from JAR (Spring Boot)

### ISSUE THREAD

**Issue by ngbalk** [GoogleCloudPlatform/app-maven-plugin#416]
I'm not convinced that this is necessary an issue with this plugin, but hoping that this community may have insight... and if this is a widespread issue with building JARs then it would certainly affect this plugin's users:

I've started to see my builds fail with the error message:
`unzipping jar /workspace/****.jar: zip: not a valid zip file`

This issue just started around 4/1/2020 when my builds suddenly started failing - when I run `mvn package appengine:deploy` the Cloud Build step fails with the following (Note: redacting personal info):
```
INFO: submitting command: /Users/*****/Library/Application Support/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/gcloud app deploy --project ******
[INFO] GCLOUD: Services to deploy:
[INFO] GCLOUD: 
[INFO] GCLOUD: descriptor:      [/Users/****/IdeaProjects/****/*****/target/appengine-staging/app.yaml]
[INFO] GCLOUD: source:          [/Users/*****/IdeaProjects/****/*****/target/appengine-staging]
[INFO] GCLOUD: target project:  [******]
[INFO] GCLOUD: target service:  [*****]
[INFO] GCLOUD: target version:  [****]
[INFO] GCLOUD: target url:      [******]
[INFO] GCLOUD: 
[INFO] GCLOUD: 
[INFO] GCLOUD: Beginning deployment of service [*****]...
[INFO] GCLOUD: #============================================================#
[INFO] GCLOUD: #= Uploading 0 files to Google Cloud Storage                =#
[INFO] GCLOUD: #============================================================#
[INFO] GCLOUD: File upload done.
[INFO] GCLOUD: Updating service [default]...
[INFO] GCLOUD: ..............................................................................................failed.
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build ec88297e-54db-4ed8-9d31-cd7a56345b23 status: FAILURE.
[INFO] GCLOUD: Build error details: {"error":{"errorType":2,"canonicalCode":2,"errorId":"63997c4b","errorMessage":"unzipping jar /workspace/****.jar: zip: not a valid zip file"}}.
```

I am using the following plugin:
```xml
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>2.2.0</version>
        <configuration>
          <deploy.version>GCLOUD_CONFIG</deploy.version>
          <deploy.projectId>*****</deploy.projectId>
        </configuration>
      </plugin>
```

And Spring Boot maven plugin:
```xml
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <executable>true</executable>
        </configuration>
      </plugin>
```

with the latest version of underlying gcloud sdk

```
Google Cloud SDK 288.0.0
bq 2.0.56
cloud-build-local 
core 2020.04.03
gsutil 4.49
``` 

And my app.yml is:
```yml
runtime: java11
instance_class: F4_HIGHMEM
env_variables:
  HEAP_SIZE_MB: 1536
```

I've verified that the packaged JAR is valid and can be executed with `java -jar` and can be expanded as an archive.   Also, I attempted to run `gcloud app deploy --project *****` directly on the built artifact and received the same error message.  

Are you aware of any update / regression with Google Cloud Build that might affect JAR (Java11) support?

**Update**: I got this working when I removed the `<executable>true</executable>` from my spring boot maven plugin configuration, so now its simply:

```
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
```

The documentation for this flag warns that this could happen:

```
Make a fully executable jar for *nix machines by prepending a launch script to the
jar. Currently, some tools do not accept this format so you may not always be able to
use this technique. For example,  jar -xf may silently fail to extract a jar
or war that has been made fully-executable. It is recommended that you only enable
this option if you intend to execute it directly, rather than running it with java -jar or deploying it to a servlet container.
```
I still suspect that there was some backwards compatibility broken here... is this known?  I'm also not sure why the build step would attempt to explode the JAR as if it were some other archive (WAR or EAR) since the [new-ish Java11 runtime](https://cloud.google.com/blog/products/application-development/app-engine-java-11-is-ga-deploy-a-jar-scale-it-all-fully-managed) [natively supports executing JARs](https://cloud.google.com/appengine/docs/standard/java11/runtime#application_startup).  Where might be a better place to file an issue with Cloud Build?

**Comment by chanseokoh** [comment]
> since the [new-ish Java11 runtime](https://cloud.google.com/blog/products/application-development/app-engine-java-11-is-ga-deploy-a-jar-scale-it-all-fully-managed) [natively supports executing JARs](https://cloud.google.com/appengine/docs/standard/java11/runtime#application_startup).

For this to work, I suspect you should define `entrypoint` yourself.
```
runtime: java11
entrypoint: java -Xmx64m -jar YOUR-ARTIFACT.jar
```

Apparently, `<executable>true` injects some bytes (actually a small shell script prepended to the actual JAR content, I believe) into a JAR, which without a doubt makes it a non-ZIP file. (Most likely the custom injection is only to allow directly running the file by `$ ./your.jar` on *nix systems.) Therefore, I'm certain that `$ unzip your.jar` or `$ jar -x your.jar` will fail. Since the custom shell script injection isn't going to be used elsewhere than on your local dev machine, I'd just turn that off when creating an artifact for deployment. You could create dev and prod Maven profiles. Unless you have a very good reason add such a script, I suggest you not do it; it's good for security too.

Whether or not GCB stopped working with this, I don't really think this is an issue on GCB. The JAR file is simply not a valid ZIP file. And unless you want to do
```
runtime: java11
entrypoint: ./YOUR-ARTIFACT.jar
```
I don't find any reason you want to manipulate your JAR. And I don't find a reason to do `./YOUR-ARTIFACT.jar` on prod either.

**Comment by ngbalk** [comment]
Thanks for the quick response - I agree with you that the  "zip" created by spring-boot-maven-plugin is out of scope for support by GCB, regardless of if it used to be supported.  Resolving the issue and hopefully this discussion may help others quickly resolve this error with a quick Google Search in the future.
