### ISSUE TITLE
ERROR: (gcloud.app.deploy) Error Response: [9]  Application startup error! Code: APP_CONTAINER_CRASHED

### ISSUE THREAD

**Issue by Kunal614** [GoogleCloudPlatform/app-maven-plugin#417]
> pxt-core@5.37.26 start /app
> pxt serve

sh: 1: pxt: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! pxt-core@5.37.26 start: `pxt serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the pxt-core@5.37.26 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-20T07_09_54_748Z-debug.log

**Comment by Kunal614** [comment]
can anyone help me out of this

**Comment by chanseokoh** [comment]
Are you using this Maven plugin? Is your app a Java app?

**Comment by Kunal614** [comment]
No no , i just deployed node js app

**Comment by loosebazooka** [comment]
This is the wrong forum for that question. This is a plugin for java applications on appengine. You might want to check here: https://cloud.google.com/appengine/community
