### ISSUE TITLE
 Failed to run devappserver

### ISSUE THREAD

**Issue by mcuozzo19** [GoogleCloudPlatform/app-maven-plugin#418]
![image](https://user-images.githubusercontent.com/34966575/83074467-d70fbe00-a037-11ea-9c46-6ff4c8d22cbf.png)
What does this error mean?

**Comment by chanseokoh** [comment]
I'd pass `-e` or -X` to get the full trace to have a better sense of the error.

**Comment by essencec** [comment]
I am also running into the same issue

evcain@cloudshell:~/step/portfolio$ mvn package appengine:run
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< com.google.sps:portfolio >----------------------
[INFO] Building portfolio 1
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ portfolio ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/evcain/step/portfolio/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ portfolio ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ portfolio ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/evcain/step/portfolio/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ portfolio ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ portfolio ---

**Comment by essencec** [comment]
I am running into a similar issue. Here is a link to my error. https://gist.github.com/essencec/ebf2eff9ce1a76748959ae6eb7b47bd4

**Comment by ajwang0** [comment]
After some debugging, we found out that Essence's issue was because something was occupying port 8080.

**Comment by chanseokoh** [comment]
@ajwang0 thanks for the update.

**Comment by essencec** [comment]
I was able to resolve the problem by using netstat -vanp tcp | grep 8080

**Comment by chanseokoh** [comment]
@mcuozzo19 we haven't heard back from you, but given the circumstances, I will assume your issue is resolved by now. I'm closing the issue, but feel free to update or reopen with more details.
