### ISSUE TITLE
The plugin always try to unzip the deployed artifact, even when it is a GraalVM native executable.

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/app-maven-plugin#420]
Playing with a Quarkus sample, and configured the plugin to use the native-image binart to deploy with a good app.yaml having its entrypoint pointing to the native binary.

On stage or deploy, getting this plugin error:
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:2.2.0:stage (default-cli) on project getting-started: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:2.2.0:stage failed: com.google.cloud.tools.appengine.AppEngineException: java.util.zip.ZipException: error in opening zip file -> [Help 1]

The plugin configuration is:
```
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>appengine-maven-plugin</artifactId>
                <version>2.2.0</version>
                <configuration>
                    <artifact>${project.build.directory}/quarkus-quickstart-runner</artifact>
                    <projectId>openjdk11</projectId>
                    <version>quarkusio-graal-native2020</version>
                    <promote>false</promote>  
                </configuration>
            </plugin>
```
So 2 bugs:
1/ when there is an app.yaml with an entrypoint, we should not try to do anything (opening, unzipping, whatever) with the artifact value we want to deploy
2/ in any case, if the artifact is not ending with .jar extension, we should not try to unzip it
3/ bonus point: if there is no app.yaml and the artifact is "executable", we could generate this default app.yaml:
```
runtime:  java11
entrypoint: the value of artifact in the plugin configuration.
```

**Comment by loosebazooka** [comment]
Yeah, I think we just assume it's always a jar and look into it to grab the correct dependencies. I'll see what we can do with this.

**Comment by ludoch** [comment]
While you are on it, I remember messing up with the content of artifact, so it did not exist.
The error message for deployment was confusing IIRC (or maybe I did not create yet the app.yaml), but I am confused!

**Comment by ludoch** [comment]
My history: I guess when no app.yaml:

[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:2.2.0:stage (default-cli) on project getting-started: 
[ERROR] Could not determine appengine environment, did you package your application?
[ERROR] Run 'mvn package appengine:stage'

The confusion is that I did a mvn package before, so the errror is not helping a lot.

**Comment by ludoch** [comment]
When there is no app.yaml and the jar is executable, gcloud app deploy myjar.jar works (by creating a simple app.yaml)

**Comment by jcfrk101** [comment]
Any updates on this, or known work arounds? I am trying to deploy a graalvm binary to an java11 runtime in app engine standard.

**Comment by loosebazooka** [comment]
@jcfrk101 this is already available in the lates release `2.3.0`. If you configure the `artifact` to a binary, it will not try to expand it.

**Comment by jcfrk101** [comment]
Is there any way to upload resource files along with the binary?

**Comment by ludoch** [comment]
Yes, see the doc for the stage goal at https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/USER_GUIDE.md

and experiment with the flag:

extraFilesDirectories | The list of directories to copy extra files from.

from where you can copy from the project area files from a given directory to the staging directory, along with the deployed artifact, so that you combine all of them before deployment...
Experiment with mvn appengine:stage and look a the appengine-stage directory in the target/ directory to see the content you can control.
