### ISSUE TITLE
New versions no longer autogenerate appengine-web.xml and web.xml? [documentation]

### ISSUE THREAD

**Issue by AugustZellmer** [GoogleCloudPlatform/app-maven-plugin#426]
As far as I can deduce, old versions of the App Engine Maven Plugin based on App Engine SDK would autogenerate the appengine-web.xml file and the web.xml file based on the contents of the app.yaml file. As far as I can deduce, new versions of the App Engine Maven Plugin based on Cloud SDK no longer autogenerate these two files. Is this change of functionality intentional? I was not able to find any documentation explaining that this functionality was intentionally removed. Is there some new process by which these two files can be autogenerated?

**Comment by loosebazooka** [comment]
I believe this feature had been deprecated for quite some time. @ludoch @eamonnmcmanus ?

**Comment by ludoch** [comment]
Right this non supported feature was removed maybe 2 years ago... I believe it was never documented publicly.
The only way to use the Java8 runtime is to define the appengine-web.xml.
If you use Servlet 3.1 annotations, you do not need web.xml anymore.
