### ISSUE TITLE
maven for app engine deployment

### ISSUE THREAD

**Issue by 1q2q** [GoogleCloudPlatform/app-maven-plugin#433]
I am deploying a app engine to gcloud and in maven step i am getting below error 

Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:2.0.0:stage (default-cli) on project core: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:2.0.0:stage failed: com.google.cloud.tools.appengine.operations.cloudsdk.AppEngineJavaComponentsNotInstalledException: Validation Error: Java App Engine components not installed. Fix by running 'gcloud components install app-engine-java' on command-line. -> [Help 1]

I have re installed the G cloud sdk and installed the app engine java manually in G cloud shell and I can see now app engine java is installed . Still am getting the same error

**Comment by 1q2q** [comment]
I have Java 1.8 installed on the server

**Comment by loosebazooka** [comment]
1. `2.0.0` is an old version of the plugin. Please use 2.4.0.
2. It is hard to determine what is going on here without seeing how you've configured your plugin, please share the relevant parts of your `pom.xml`

**Comment by 1q2q** [comment]
hi please see the pom.xml 

<dependencies>
        <dependency>
            <groupId>org.glassfish.jersey.containers</groupId>
            
            <artifactId>jersey-container-servlet-core</artifactId>
            <version>2.23.2</version>
        </dependency>
        
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>2.23.2</version>
        </dependency>

        <dependency>
            <groupId>com.google.dagger</groupId>
            <artifactId>dagger</artifactId>
            <version>2.2</version>
        </dependency>

        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>${jax-rs.version}</version>
        </dependency>

        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>servlet-api</artifactId>
            <version>2.5</version>
        </dependency>

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud</artifactId>
            <version>0.5.1</version>
        </dependency>

        <dependency>
            <groupId>com.google.appengine</groupId>
            <artifactId>appengine-api-1.0-sdk</artifactId>
            <version>1.9.44</version>
        </dependency>

        <dependency>
            <groupId>org.immutables</groupId>
            <artifactId>value</artifactId>
            <version>2.3.7</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
            <version>2.24</version>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>20.0</version>
        </dependency>

        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-drive</artifactId>
            <version>v2-rev393-1.25.0</version>
        </dependency>

        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.10</version>
            <exclusions>
                <exclusion>
                    <groupId>org.javassist</groupId>
                    <artifactId>javassist</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.javassist</groupId>
            <artifactId>javassist</artifactId>
            <version>3.18.2-GA</version>
        </dependency>

        <dependency>
            <groupId>com.appsbroker.libgoogle</groupId>
            <artifactId>libdrive</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.appsbroker.libgoogle</groupId>
            <artifactId>libcredentials</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.appsbroker.libgoogle</groupId>
            <artifactId>libgroups</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.appsbroker.libgoogle</groupId>
            <artifactId>libdirectory</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>4.3.1.Final</version>
        </dependency>

        <dependency>
            <groupId>javax.el</groupId>
            <artifactId>javax.el-api</artifactId>
            <version>2.2.4</version>
        </dependency>

        <dependency>
            <groupId>org.glassfish.web</groupId>
            <artifactId>javax.el</artifactId>
            <version>2.2.4</version>
        </dependency>


        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.9.5</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.glassfish.jersey.test-framework.providers</groupId>
            <artifactId>jersey-test-framework-provider-grizzly2</artifactId>
            <version>2.24</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.google.appengine</groupId>
            <artifactId>appengine-testing</artifactId>
            <version>1.9.44</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.appengine</groupId>
            <artifactId>appengine-api-stubs</artifactId>
            <version>1.9.44</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.appengine</groupId>
            <artifactId>appengine-api-labs</artifactId>
            <version>1.9.44</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-oauth2</artifactId>
            <version>v2-rev98-1.21.0</version>
        </dependency>

        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.25-incubating</version>
        </dependency>

    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>**/*.p12</exclude>
                </excludes>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.p12</include>
                </includes>
                <filtering>false</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <version>3.1</version>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <forceJavacCompilerUse>true</forceJavacCompilerUse>
                </configuration>

                <dependencies>
                    <dependency>
                        <groupId>com.google.dagger</groupId>
                        <artifactId>dagger-compiler</artifactId>
                        <version>2.2</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>appengine-maven-plugin</artifactId>
                <version>2.0.0</version>
                <configuration>
                    <project>${projectId}</project>
                    <devserver.host>0.0.0.0</devserver.host>
                    <devserver.port>8181</devserver.port>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.2.2</version>
                <configuration>
                    <archiveClasses>true</archiveClasses>
                    <webResources>


                        
                        <resource>
                            <directory>${basedir}/src/main/webapp/WEB-INF</directory>
                            <filtering>true</filtering>
                            <targetPath>WEB-INF</targetPath>
                        </resource>

                        <resource>
                            <directory>${basedir}/src/main/webapp/META-INF</directory>
                            <targetPath>WEB-INF/classes/META-INF</targetPath>
                        </resource>

                        <resource>
                            <directory>src/main/resources</directory>
                            <filtering>true</filtering>
                            <excludes>
                                <exclude>**/*.p12</exclude>
                            </excludes>
                            <targetPath>WEB-INF</targetPath>
                        </resource>

                        <resource>
                            <directory>src/main/resources</directory>
                            <filtering>false</filtering>
                            <includes>
                                <include>**/*.p12</include>
                            </includes>
                            <targetPath>WEB-INF</targetPath>
                        </resource>

                        
                        <resource>
                            <directory>${basedir}/src/main/webapp</directory>
                            <filtering>true</filtering>
                            <includes>
                                <include>cron.yaml</include>
                            </includes>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by loosebazooka** [comment]
Version 2.0.0 should be automatically downloading and installing the cloud sdk.

Can you check the contents of the automatically installed cloud sdk? In your case `<version>` is probably `LATEST`
```
The Cloud SDK is installed in $USER_HOME/.cache/google-cloud-tools-java/managed-cloud-sdk/<version>/google-cloud-sdk on Linux, $USER_HOME/Library/Application Support/google-cloud-tools-java/managed-cloud-sdk/<version>/google-cloud-sdk on OSX, and %LOCALAPPDATA%/google/ct4j-cloud-sdk/<version>/google-cloud-sdk on Windows.
```

**Comment by 1q2q** [comment]
I am not able to find the automatically installed sdk on the localappdata path in my windows server

**Comment by loosebazooka** [comment]
You can try configuring the cloudSdkHome parameter to explicitly point to your installation location:

https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/USER_GUIDE.md#cloud-sdk-configuration

**Comment by 1q2q** [comment]
C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk - this is the path where actual GSDK we have installed on server

**Comment by loosebazooka** [comment]
Does that work?

**Comment by 1q2q** [comment]
<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">
    
    <threadsafe>true</threadsafe>
    <sessions-enabled>true</sessions-enabled>
    <runtime>java8</runtime>
    <url-stream-handler>urlfetch</url-stream-handler>

    
    <system-properties>
        <property name="java.util.logging.config.file" value="WEB-INF/logging.properties"/>
        <property name="appengine.api.urlfetch.defaultDeadline" value="50"/>
    </system-properties>

    
    <static-files>
        <include path="/assets/**.*"/>
        <include path="**.svg">
            <http-header name="Content-Type" value="image/svg+xml"/>
        </include>
    </static-files>
</appengine-web-app>


This is the app-engine xml file I have , are you saying we need to configure path to sdk with in xml and build?

**Comment by loosebazooka** [comment]
If you're not familiar with maven, I suggest reading through a maven guide before proceeding.

Anyway, in your `pom.xml`, following the instructions in the user guide: https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/USER_GUIDE.md#cloud-sdk-configuration

You would have to add to the existing `appengine-maven-plugin` block a new `<configuraiton>` option of `<cloudSdkHome>`
```
 <plugin>
            <groupId>com.google.cloud.tools</groupId>
            <artifactId>appengine-maven-plugin</artifactId>
            <version>2.0.0</version>
            <configuration>
                <project>${projectId}</project>
                <devserver.host>0.0.0.0</devserver.host>
                <devserver.port>8181</devserver.port>
                <!-- add this option -->
                <cloudSdkHome>C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk</cloudSdkHome>
            </configuration>
 </plugin>
```

**Comment by 1q2q** [comment]
I updated the pom.xml with GSDK path and now got this error 
Sep 21, 2020 6:06:06 PM com.google.cloud.tools.appengine.operations.AppCfgRunner run
INFO: submitting command: C:\Program Files\Java\jdk1.8.0_211\jre\bin\java.exe -cp C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\lib\appengine-tools-api.jar com.google.appengine.tools.admin.AppCfg --disable_update_check stage F:\folder_Dotnet&JavaAgent_server\_work\1\s\app\core\target\core-0.0.1-local F:\folder_Dotnet&JavaAgent_server\_work\1\s\app\core\target\appengine-staging
[INFO] GCLOUD: Reading application configuration data...
[INFO] GCLOUD: 2020-09-21 18:06:07.750:INFO::main: Logging initialized @985ms
[INFO] GCLOUD: 
[INFO] GCLOUD: 
[INFO] GCLOUD: Beginning interaction for module default...
[INFO] GCLOUD: 0% Scanning for jsp files.
[INFO] GCLOUD: 0% Generated git repository information file.
[INFO] GCLOUD: Success.
[INFO] GCLOUD: Temporary staging for module default directory left in F:\fodler_Dotnet&JavaAgent_server\_work\1\s\app\core\target\appengine-staging
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.687 s
[INFO] Finished at: 2020-09-21T18:06:09+02:00
[INFO] ------------------------------------------------------------------------
Could not retrieve code analysis results - Maven run failed.
##[error]Build failed.
Finishing: Maven Staging

**Comment by 1q2q** [comment]
@loosebazooka loosebazooka: Post i updated the sdkhome path I ran the build and ignored the error as mentioned for maven and it deployed as expected . Thanks
