### ISSUE TITLE
dispatch.yaml is not getting deployed in devserver

### ISSUE THREAD

**Issue by mahesh-thirunavukarasu** [GoogleCloudPlatform/app-maven-plugin#437]
dispatch.yaml is not getting deployed in devserver (appengine : run). Any specific reason for the same? Also, As I am working on a maven multimodule, I find it very difficult to target each individual port as a workaround (as multiple services are running in different random ports). The same feature is available for the python 2.7 but not in java 8. Hence I am curious to know the reason, and any possible workaround is much appreciated.

**Comment by chanseokoh** [comment]
The [doc](https://cloud.google.com/appengine/docs/standard/java/how-requests-are-routed#dispatch_files) says

> #### Dispatch files
> All dispatch files are ignored when running the local development server. The only way to target instances is through their ports.

For the port issue, can you try and see if this workaround works? https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/235#issuecomment-356014144

**Comment by mahesh-thirunavukarasu** [comment]
sorry, the above suggestion did not work. But thank you for suggesting. Since I am new to appengine development, I somehow need suggestions to debug the multi module app in eclipse. I also tried remote debugging through eclipse, but getting "unable to connect to VM", Connection refused error
