### ISSUE TITLE
api_version error when app.yaml is autogenerated

### ISSUE THREAD

**Issue by diegoruizgx** [GoogleCloudPlatform/app-maven-plugin#442]
When app.yaml is autogenerated using appengine-web.xml, the api version got always user_defined
`api_version: 'user_defined'`

**Comment by loosebazooka** [comment]
Not sure what's going on, clould be coming from the appengine sdk tooling. @ludoch @eamonnmcmanus ?

**Comment by ludoch** [comment]
Yes, intended.
Now, the api jar is always bundled with the deployed app from whatever version defined in pom.xml and its version is inside the jar (in the manifest).
