### ISSUE TITLE
feature request/doubt: caching cloudsdk in ci

### ISSUE THREAD

**Issue by alex-ioma** [GoogleCloudPlatform/app-maven-plugin#449]
Hi there, 

I've been trying without success to cache the downloaded the Cloud SDK in Gitlab CI. 

Preferred behavior: 
- Use `cloudSdk` variable define a path in .m2 where to download and save the SDK
- Keep `cloudSdkVersion` undefined (or set to LATEST)
- Runner downloads SDK at first job
- Cache it via cache declaration in `.gitlab-ci.yaml`
- When a new job is schedule, cache is retrieved and plugin looks if the SDK version is updated to latest; if not, the new version is downloaded so that the runner can cache it after pipeline completion

Current behavior: 
- The first job fails as cloduSdk is not found at location

In general, I'm never able to cache the SDK even if I unset the cloudSDK variable and set cache declaration in `.gitlab-ci.yaml` to `/root/...`

In this last case, the SDK is downloaded each time a job runs.

Is it a missing perf feature or am I doing something wrong?

**Comment by chanseokoh** [comment]
I believe you meant `cloduSdkHome`. As the [doc](https://cloud.google.com/appengine/docs/standard/java/maven-reference) says, if you define it, the plugin will NOT download a Cloud SDK. The parameter is to prevent the plugin from automatically managing Cloud SDK but instead make it use an existing Cloud SDK installation that you decide to install and manage yourself.

So, one option you can do on your CI is to manually download and unzip Cloud SDK to some directory, set `cloudSdkHome` to that directory, and have GitLab cache it.

But probably, it may be more convenient to let the plugin download an SDK. You can check the location where the managed SDK resides [here](https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/USER_GUIDE.md#cloud-sdk-configuration). So I guess it's just a matter of caching, e.g., `$USER_HOME/.cache/google-cloud-tools-java/managed-cloud-sdk/` on Linux. You should be able to see in logs where it is being downloaded, e.g.,:

```
testRunAsync: [INFO] --- appengine-maven-plugin:2.4.2-SNAPSHOT:start (default-cli) @ standard-project ---
testRunAsync: [INFO] Waiting 60 seconds for the Dev App Server to start.
testRunAsync: Aug 05, 2021 2:37:59 PM com.google.cloud.tools.managedcloudsdk.install.Downloader download
testRunAsync: INFO: Downloading https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz to /home/runner/.cache/google-cloud-tools-java/managed-cloud-sdk/downloads/google-cloud-sdk.tar.gz
```

**Comment by alex-ioma** [comment]
Thank you but perhaps I wasn't clear in my description. 

I'm aware that if `cloudSdkHome` is set the plugin doesn't download the SDK. But the issue here is that if I use the default directory the CI is not able to cache a `/root/.cache/google-cloud-tools-java/...`. 

If I do as you suggested the result is the following: 
```
Creating cache develop...
.m2/repository: found 4548 matching files and directories 
WARNING: ~/.cache/google-cloud-tools-java/managed-cloud-sdk/: no matching files 
Uploading cache.zip to https://storage.googleapis.com/gitlab-com-runners-cache/project/[redacted]
Created cache
```

Thus the question (which better phrase would be a feature request) to add a different management in the plugin, e.g. adding another `cloudSdkDownload` boolean in addition to `cloudSdkHome`. This way a user would have control whether to set/move the SDK and ask the plugin to check the presence o the SDK and download it if absent. 

The issue with adding an additional set in the CI to download and unpack the SDK at a given location (as suggested) is unpractical since it would be a one time steps that would be removed later on in the CI. At which point, a cache clean would break the CI altogether. 

Likewise, adding a job that check plugin presence and download it if absent, completely defeats the purpose of this plugin instead. Because at that point it would be much better to avoid the use if this plugin (which is otherwise very nice) and simply deploy with standard gcloud image command.

Am I perhaps missing something in why the runner is not caching the default SDK location? 

Thanks!

**Comment by chanseokoh** [comment]
To disappointment you (sorry), I don't think we'll add a feature to let the user chose the location of the managed Cloud SDK.

> unpractical since it would be a one time steps that would be removed later on in the CI. At which point, a cache clean would break the CI altogether.

The way I would set up this is to download the SDK only when the target directory missing. Nonetheless, as you said, because the plugin auto-downloads it, I wouldn't manually download it. That's why I said "but probably, it may be more convenient to let the plugin download it."

What I suspect about `~/.cache/google-cloud-tools-java/...` empty: the interpretation of `~`, `$HOME`, or the notion of a "home directory" of a user on the bash environment or in JVM may be different from what you may be thinking. I would check the Maven console logs to figure out the exact download path. I would also do `ls /root/.cache`, etc., and also check the user of the JVM process.

The fact is that, the plugin is downloading an SDK and it exists somewhere (otherwise, I believe your CI will just fail.) So, it's just a matter of your figuring out the exact location and having GitLab cache it.

**Comment by alex-ioma** [comment]
I though about the possible issue of `~` and I also tried to cache the absolute path in `/root` since this is appears to be where the plugin is downloaded from the maven console. 

But adding a simple `ls` to troubleshoot what is going wrong actually is a great idea. 

Thanks for the advice!

**Comment by alex-ioma** [comment]
UPDATE: I'm afraid `/root` cache is known issue on git. See [this reference](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/327). 

Apparently there is not much way to work around it than having ti downloaded every single build. 

Thanks anyway.

**Comment by chanseokoh** [comment]
You can tell your JVM that the "user home" is different than `/root` with the system property, e.g., `-Duser.home=/another/home`.
