### ISSUE TITLE
Support and Test JDK17

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/app-maven-plugin#453]
## Expected

JDK 17 reached General Availability on 14 September 2021. This repo should test JDK 17.

## Actual

JDK 17 is not tested. Just 8 and 11:

https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/master/.github/workflows/unit-tests.yaml

**Comment by ludoch** [comment]
FYI, GAE Java17 is currently in the work. https://github.com/GoogleCloudPlatform/buildpacks/tree/e1dfd783f710dae1b74ba16ddd3b769218b50982/builders/gae/java17 including gen1 GAE API standard support.

**Comment by mpeddada1** [comment]
Thank you for filing the issue @grant and the additional details on GAE Java 17 support @ludoch! Yes, it'll be good to check if this works without the need for any additional changes for the maven plugin.

**Comment by grant** [comment]
Thanks. For reference, Java 17 support is a P0 OKR for serverless runtimes. I'll be monitoring this repo and other dependencies.

**Comment by grant** [comment]
Sync'd on this issue on VC. FYI I won't be blocked on anything here but we can keep track of notes here. There may be some common dependencies that need updating.

Will file issues as I come across them.

**Comment by ludoch** [comment]
Any update on progress?

**Comment by elefeint** [comment]
This was done for runtime compatibility for both maven and gradle plugins. The maven portion was in #455 and #456. The last bit for local devserver was done by pulling in appengine-plugins-core 0.9.9.

**Comment by ludoch** [comment]
Thank you!
