### ISSUE TITLE
Can't deploy GAE Standard with artifact registry enabled

### ISSUE THREAD

**Issue by lvalladares** [GoogleCloudPlatform/app-maven-plugin#468]
Since GCP is stopping the support for container registry and the new service that will replace this is the artifact registry, I tried to enable it on my project and route all the traffic to the Artifact Registry.

But when I try to deploy my GAE Standard Java 8 APP I get the following error: https://pastebin.com/7ACDeU1b

When I change the routing and make it go through the container registry everything starts working again.

**Comment by elefeint** [comment]
@lvalladares Could you provide a minimal reproducible sample demonstrating the issue?

**Comment by chanseokoh** [comment]
This is unrelated to the plugin and should be reproducible just with `gcloud app deploy`. There's nothing we can fix on the plugin side.

**Comment by lvalladares** [comment]
@chanseokoh Yes you are right, its reproducible with gcloud app deploy.

Where can I report this?
