### ISSUE TITLE
test cases include the application id and version in the appengine-web.xml

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/app-maven-plugin#67]
storing the ID and version in the appengine-web.xml is no longer the recommended way to do it, and technically shouldn't work against the gcloud tooling.

**Comment by meltsufin** [comment]
App Engine Staging currently requires the `<application>` element. If not provided, it throws this error message: `Bad configuration: No app id supplied and XML files have no <application> element`.

**Comment by meltsufin** [comment]
Internal reference ID for tracking AppCfg staging fix: 31177580

**Comment by meltsufin** [comment]
@patflynn is <version> supposed to be translated into app.yaml by AppCfg staging? It doesn't seem to be  happening.

**Comment by patflynn** [comment]
What is supposed to be translated?

**Comment by meltsufin** [comment]
`<version>{version}</version>` in appengine-web.xml to `version: {version}` in app.yaml

**Comment by patflynn** [comment]
my understanding is that both version and application are stripped

**Comment by patflynn** [comment]
@meltsufin @loosebazooka can we close this?
