### ISSUE TITLE
BUG: -Dapp.

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/app-maven-plugin#81]
Trying to build [helloworld](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/managed_vms/helloworld) on Jenkins with:

    mvn clean appengine:deploy -Dapp.deploy.version=java-mvm-helloworld -Dapp.deploy.promote=false -DcloudSdkPath=/usr/local/share/google/google-cloud-sdk

The `-Dapp.deploy.promote=false` should be able to [override](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/managed_vms/helloworld/pom.xml#L60-L69):

        <configuration>
          
          <deploy.promote>true</deploy.promote>
          <deploy.stopPreviousVersion>true</deploy.stopPreviousVersion>
        </configuration>

I probably should remove these from the samples, but it would be nice if it worked in a logical way.

**Comment by lesv** [comment]
@ludoch FYI

**Comment by meltsufin** [comment]
It looks like this is just the default behavior of Maven plugins in general. Parameters defined in the configuration section cannot be overwritten from command-line without special tricks.
See: http://stackoverflow.com/questions/23391502/whats-the-meaning-of-user-property-of-maven-plugin-parameter
See: http://jira.codehaus.org/browse/MNG-4979

**Comment by lesv** [comment]
Sigh - I guess I usually use the tricks.
