### ISSUE TITLE
Multiple modules with different runtimes

### ISSUE THREAD

**Issue by GabiAxel** [GoogleCloudPlatform/app-maven-plugin#82]
Greetings,

If I understand correctly, for standard environment, this plugin is designed to work in a directory which contains `WEB-INF/appengine-web.xml`. I would like to use it to run the development server with a project that contains a Java default module and a Python module (for that matter it can be any non-Java runtime) and I couldn't find any way to do it with the maven plugin (setting appYamls didn't seem to help).

I can implement what I want when using the App Engine Java Client Library directly like so:

```java
DefaultRunConfiguration config = new DefaultRunConfiguration();
config.setAppYamls(Arrays,asList(
  new File("/java-module-dir/target/..."),
  new File("/python-module-dir")
));
new CloudSdkAppEngineDevServer(new CloudSdk.Builder().build()).run(config);
```

Is there a way to do it with the Maven plugin? If not, may I suggest adding it?

**Comment by meltsufin** [comment]
Hi Gabi! You're right, what you're trying to do should work. In fact, I've just tested a similar setup using the maven plugin and it worked for me.

What is the error message that you see in the console when you try to run the plugin goal?

Here's my setup:

**Python Module Config: /tmp/python-docs-samples/appengine/standard/hello_world/app.yaml**
```
runtime: python27
api_version: 1
threadsafe: true
service: python

handlers:
- url: /.*
  script: main.app
```
**Java Module Config: /tmp/java-docs-samples/appengine/helloworld-new-plugins/src/main/webapp/WEB-INF/appengine-web.xml**
```XML
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">
  <service>java</service>
  <threadsafe>true</threadsafe>
</appengine-web-app>
```

**App Engine Maven Plugin Confing: /tmp/java-docs-samples/appengine/helloworld-new-plugins/pom.xml**
```XML
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>0.1.2</version>
        <configuration>
          <appYamls>
            <param>/tmp/python-docs-samples/appengine/standard/hello_world/app.yaml</param>
            <param>target/appengine-helloworld-newplugins-1.0-SNAPSHOT/</param>
          </appYamls>
        </configuration>
      </plugin>
```

**Run command in /tmp/java-docs-samples/appengine/helloworld-new-plugins**
```
mvn clean appengine:run
```

**Comment by GabiAxel** [comment]
This is weird. I tried to do the same thing but it's like `appYamls` is completely ignored - the devserver always runs only the Java module. The behaviour is the same regardless of the paths in `appYamls` exist or not - there is no error for incorrect paths. I tested with absolute paths, relative paths and incorrect paths, result is the same.

I run Maven with debug output and found two references to `appYamls`. First I see the paths from the POM:

```
[DEBUG] Goal:          com.google.cloud.tools:appengine-maven-plugin:0.1.2:run (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <adminHost>${app.devserver.adminHost}</adminHost>
  <adminPort>${app.devserver.adminPort}</adminPort>
  <allowSkippedFiles>${app.devserver.allowSkippedFiles}</allowSkippedFiles>
  <apiPort>${app.devserver.apiPort}</apiPort>
  <appYamls default-value="${project.build.directory}/${project.build.finalName}">
    <param>/tmp/python-docs-samples/appengine/standard/hello_world/app.yaml</param>
    <param>target/appengine-helloworld-newplugins-1.0-SNAPSHOT/</param>${app.devserver.appYamls}</appYamls>
    ... many other configurations...
</configuration>
```

and later it's the Java module's build directory:

```
[DEBUG] Configuring mojo 'com.google.cloud.tools:appengine-maven-plugin:0.1.2:run' with basic configurator -->
[DEBUG]   (f) appYamls = [/java-module/target/java-module-0.0.1-SNAPSHOT]
```

Any idea what it could be or what I should check?

**Comment by meltsufin** [comment]
Are you seeing any errors in the console at all?

When you run `mvn appengine:run`, you should see the command that it's actually executing to start the dev appserver. Can you paste the output from that line on?
Here's what I get:
```
INFO: submitting command: /usr/local/home/meltsufin/apps/google-cloud-sdk/bin/dev_appserver.py /tmp/python-docs-samples/appengine/standard/hello_world/app.yaml /tmp/java-docs-samples/appengine/helloworld-new-plugins/target/appengine-helloworld-newplugins-1.0-SNAPSHOT --jvm_flag=-Dappengine.user.timezone=UTC
[INFO] GCLOUD: INFO     2016-09-15 20:09:01,413 devappserver2.py:769] Skipping SDK update check.
[INFO] GCLOUD: INFO     2016-09-15 20:09:01,440 api_server.py:205] Starting API server at: http://localhost:52942
[INFO] GCLOUD: INFO     2016-09-15 20:09:01,442 dispatcher.py:197] Starting module "python" running at: http://localhost:8080
[INFO] GCLOUD: INFO     2016-09-15 20:09:01,443 dispatcher.py:197] Starting module "java" running at: http://localhost:8081
[INFO] GCLOUD: INFO     2016-09-15 20:09:01,444 admin_server.py:116] Starting admin server at: http://localhost:8000
[INFO] GCLOUD: WARNING  2016-09-15 20:09:01,444 devappserver2.py:835] No default module found. Ignoring.
```

Notice that the two modules are starting on two different ports, 8080, and 8081.

**Comment by GabiAxel** [comment]
There are no errors in the console. This is how the output looks:

```
Sep 15, 2016 10:51:19 PM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: /java-module-frontend-0.0.1-SNAPSHOT --jvm_flag=-Dappengine.user.timezone=UTC
[INFO] GCLOUD: INFO     2016-09-15 19:51:21,390 devappserver2.py:769] Skipping SDK update check.
[INFO] GCLOUD: INFO     2016-09-15 19:51:21,420 api_server.py:205] Starting API server at: http://localhost:58356
[INFO] GCLOUD: INFO     2016-09-15 19:51:21,423 dispatcher.py:197] Starting module "java" running at: http://localhost:8080
[INFO] GCLOUD: INFO     2016-09-15 19:51:21,424 admin_server.py:116] Starting admin server at: http://localhost:8000
```

When I run app_devserver.py manually or use the Java client library, the two modules are up and mapped to port 8080 and 8081 as in your example.

**Comment by meltsufin** [comment]
You can see from the command, that your configuration for the appYamls is not being picked up.
```
INFO: submitting command: /java-module-frontend-0.0.1-SNAPSHOT --jvm_flag=-Dappengine.user.timezone=UTC
```

Only one module (the default) is passed in. I think it has something to do with the `default-value` attribute on `<appYamls>` in you pom.xml. Can you try removing this attribute?
```
default-value="${project.build.directory}/${project.build.finalName}"
```

**Comment by GabiAxel** [comment]
Upgrading from Maven 3.3.3 to 3.3.9 resolved it. I missed this detail in the docs, sorry. Thanks for the help.
