### ISSUE TITLE
dispatch.xml not staged

### ISSUE THREAD

**Issue by GabiAxel** [GoogleCloudPlatform/app-maven-plugin#83]
Greetings,

I'm not sure if the problem is in the Maven plugin or in one of its dependencies. When staging (or deploying) a Java standard runtime app, `dispatch.xml` is not staged as `dispatch.yaml`. Other files - `appengine-web.xml`, `cron.xml`, `datastore-indexes.xml` and `queue.xml` get staged as YAML files fine, the problem is specific to `dispatch.xml`.

I also tried to add dispatch.yaml in several places in the project and added its path to  `deployables`, but it never got copied to to `appengine-staging`. Is there a way to do it? It doesn't matter to me if I use XML or YAML.

**Comment by meltsufin** [comment]
@ludoch Do you know if AppCfg handles dispatch.xml to dispatch.yaml translation?

**Comment by ludoch** [comment]
need to use this flag:- D/--auto_update_dispatch flag in the staging phase. I guess the app maven plugin needs to set it up?

**Comment by meltsufin** [comment]
`--auto_update_dispatch` flag causes `AppCfg stage` to attempt to upload `dispatch.xml` instead of translating it.
Internal bug ref: b/31596802

**Comment by meltsufin** [comment]
@GabiAxel Thanks for your issue report. It indeed appears to be a bug in a dependency of the plugin. We're working on resolving it.

In the meantime, you can try putting `dispatch.yaml` in your `src/main/resources`, which will cause it to be copied to `target/appengine-staging/WEB-INF/classes/dispatch.yaml`. Then you should be able to get everything working with a plugin config like this one:
```XML
    <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>0.1.2</version>
        <configuration>
          <deployables>
            <param>target/appengine-staging/app.yaml</param>
            <param>target/appengine-staging/WEB-INF/classes/dispatch.yaml</param>
            <!-- OTHER YAML FILES -->
          </deployables>
        </configuration>
      </plugin>
```

**Comment by patflynn** [comment]
@meltsufin question:  Could the user point the deployable to the src path? 
e.g. 
```
        <configuration>
          <deployables>
            ...
            <param>src/main/resources/dispatch.yaml</param>
            <!-- OTHER YAML FILES -->
          </deployables>
        </configuration>
```

Also I guess app.yaml is not necessary right?  I think we want to avoid highlighting app.yaml as a deployable. From the client's point of view it should be the appengine-web.xml.

**Comment by meltsufin** [comment]
Pointing directly to src path should work also, but I haven't tested it.
I believe specifying app.yaml is necessary when you're deploying more than one yaml at the same time.

**Comment by patflynn** [comment]
I'm wondering if a better approach to multi-module deployment is a parent
pom with each module deploying just one app and the parent deploying the
config yamls.

e.g.
module1/pom.xml (app-maven-plugin configured to deploy module1)
module1/src/main/webapp/WEB-INF/appengine-web.xml
module2/pom.xml (app-maven-plugin configured to deploy module2)
module2/src/main/webapp/WEB-INF/appengine-web.xml
config/prod/dispatch.yaml,cron.yaml,etc
pom.xml (app-maven-plugin configured to deploy yamls)

mvn appengine:deploy from the parent would deploy everything.

Similarly with Gradle.

And of course if the user wanted to they could just include the config
yamls with one of their modules.

**Comment by loosebazooka** [comment]
I believe this is fixed now.
