### ISSUE TITLE
Support for multiple modules/services?

### ISSUE THREAD

**Issue by aleemstreak** [GoogleCloudPlatform/app-maven-plugin#84]
Does this plugin support running multiple services/modules in the dev environment simultaneously (and respecting the dispatch file)?

**Comment by aleemstreak** [comment]
Can't seem to find an example of this, sorry if I missed it

**Comment by meltsufin** [comment]
You should be able to run multiple modules by using the `appYamls` parameter. See #82 for a related discussion and an example.
