### ISSUE TITLE
:deploy goal should quietly skip non-war projects

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/app-maven-plugin#85]
If you attempt to setup a common `appengine:deploy` from a parent pom, the maven plugin fails as its trying to deploy the `<packaging>pom</packaging>` project.

If it encounters a non-war packaging, it should just skip the `appengine:deploy` attempt. 

[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:0.1.2:deploy (deploy-integration-test) on project tests-webapps-parent: Execution deploy-integration-test of goal com.google.cloud.tools:appengine-maven-plugin:0.1.2:deploy failed: Artifact doesn't exist at '/home/joakim/code/jetty/gcloud.project/jetty-runtime/tests/webapps/target/tests-webapps-parent-0.1.0-SNAPSHOT.pom' -> [Help 1]

**Comment by meltsufin** [comment]
This would need to be done for every goal in the plugin. Jar modules are OK too. We needs to see if this is a common practice for plugins that act on war modules to skip pom modules.

**Comment by patflynn** [comment]
@meltsufin did you ever look into this?

**Comment by meltsufin** [comment]
I haven't, but it shouldn't be difficult to implement. We should look at other similar projects and see if it's a common pattern to skip over pom modules.

**Comment by joakime** [comment]
Examples of other mojo's that do the project.packaging specific behavior ...

Source Links:

* [maven-pmd-plugin](https://github.com/apache/maven-plugins/blob/cc8a226035d9f55b6f3c155b1e5d8552a0114efb/maven-pmd-plugin/src/main/java/org/apache/maven/plugin/pmd/AbstractPmdViolationCheckMojo.java#L111-L119)
* [maven-gpg-plugin](https://github.com/apache/maven-plugins/blob/8762d5746501b894cf766f38111fc514938be280/maven-gpg-plugin/src/main/java/org/apache/maven/plugin/gpg/GpgSignAttachedMojo.java#L126-L127)
* [maven-source-plugin](https://github.com/apache/maven-plugins/blob/8762d5746501b894cf766f38111fc514938be280/maven-source-plugin/src/main/java/org/apache/maven/plugins/source/AggregatorSourceJarMojo.java#L44-L47)
* [maven-site-plugin](https://github.com/apache/maven-plugins/blob/8762d5746501b894cf766f38111fc514938be280/maven-site-plugin/src/main/java/org/apache/maven/plugins/site/descriptor/SiteDescriptorAttachMojo.java#L75-L80)
* [maven-repository-plugin](https://github.com/apache/maven-plugins/blob/8762d5746501b894cf766f38111fc514938be280/maven-repository-plugin/src/main/java/org/apache/maven/plugins/repository/BundleCreateMojo.java#L175-L185)
* [maven-deploy-plugin](https://github.com/apache/maven-plugins/blob/8b357d874b7b8ab12b33d536918542a50b7d0926/maven-deploy-plugin/src/main/java/org/apache/maven/plugins/deploy/DeployFileMojo.java#L376-L377)

**Comment by loosebazooka** [comment]
@akerekes any change you can look at this when you have a chance?
