### ISSUE TITLE
Would like a new goal to set maven properties from gcloud config

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/app-maven-plugin#86]
Similar to how the mojohaus [`properties-maven-plugin`](http://www.mojohaus.org/properties-maven-plugin/).

It would be nice if a maven property could be set from the gcloud active/default project id.

**Comment by patflynn** [comment]
@joakime Hi Joakime.  Thank you for filing this and sorry for the delay.  Can you be more specific by what you mean by 'set from the gcloud active/default project id'?

**Comment by akerekes** [comment]
@joakime Is this feature to set properties from `gcloud config get-value <name>`?
