### ISSUE TITLE
Incompatibility with appengine-gcs-client (also happens with gcloud-maven-plugin)

### ISSUE THREAD

**Issue by GabiAxel** [GoogleCloudPlatform/app-maven-plugin#87]
Greetings,

I encountered an exception with appengine-gcs-client 0.6 which was already reported in the gcloud-maven-plugin project: https://github.com/GoogleCloudPlatform/gcloud-maven-plugin/issues/100 and I wanted to report that the same happens with appengine-maven-plugin 0.1.2 , so when it's fixed for one plugin please make sure to fix it in the other too.

**Comment by meltsufin** [comment]
This appears to be a problem between the Dev App Server and and appengine-gcs-client.
Tracking issue here: https://github.com/GoogleCloudPlatform/appengine-gcs-client/issues/48
