### ISSUE TITLE
Incompatibility with com.google.appengine:appengine-maven-plugin for relesign cron jobs

### ISSUE THREAD

**Issue by gadaldo** [GoogleCloudPlatform/app-maven-plugin#89]
Hi,

I have problem having the two plugins in the same pom:

1) _com.google.cloud.tools:appengine-maven-plugin 0.1.2_

2) _com.google.appengine:appengine-maven-plugin 1.9.42_

The first I use to deploy my flexible application on Google Cloud Platform, the second is useful for deploy (update_cron) the cron job xml file I have under WEB-INF folder of my project. I can't run` mvn appengine:deploy` and `appengine:update_cron` if I have both seen they have the same name but different goals.

I was wondering how can I deploy a cron job with `com.google.cloud.tools:appengine-maven-plugin 0.1.2` but looks like it does not cope with this scope so I used the command `appcfg.sh update_cron target/project-name` but this causes problems when I have to do so in a continuos integration tools such as Jenkins/Hudson/Gocd because I cant' install Google Appengine SDK on that server. 

Thank you

**Comment by meltsufin** [comment]
There are two ways you can solve this.

1) Use the fully qualified plugin name instead of the prefix.
```
mvn clean com.google.cloud.tools:appengine-maven-plugin:deploy
```

2) Deploy the app and cron configuration using com.google.cloud.tools:appengine-maven-plugin:0.1.2. (**Recommended**)

Note that `cron.yaml` is generated from `cron.xml` during staging when using the new `appengine-maven-plugin:0.1.2`. Look inside `target/appengine-staging`.
So, if you want to deploy your app and cron configuration at the same time, your plugin config should look something like this:
```XML
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>0.1.2</version>
        <configuration>
          <deployables>
            <param>target/appengine-staging/app.yaml</param>
            <param>target/appengine-staging/cron.yaml</param>
          </deployables>
        </configuration>
      </plugin>
```

**Comment by gadaldo** [comment]
Really appreciated this shout. Thank you

**Comment by meltsufin** [comment]
Happy it helped. Cheers!

**Comment by patflynn** [comment]
Perhaps we should open a documentation bug for this?

**Comment by gadaldo** [comment]
Looks like this part is missing, reading in around from Google Doc. Also I suggest to use: 

```
<deployables>
						<param>${project.build.directory}/appengine-staging/app.yaml</param>
						<param>${project.build.directory}/appengine-staging/cron.yaml</param>
					</deployables>
```

rather than 'target'.

thank you

**Comment by meltsufin** [comment]
@patflynn Tracking doc bug here: #90.
