### ISSUE TITLE
Deploy should not fail for runtime:java and empty src/main/docker directory

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/app-maven-plugin#91]
```
com.google.cloud.tools:appengine-maven-plugin:0.1.2:deploy (default-cli) on project <project>: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:0.1.2:deploy failed: Docker directory <project dir>/src/main/docker does not contain Dockerfile
```

**Comment by chanseokoh** [comment]
Note that the directory wasn't empty in @saturnism's log; it contained `Dockerfile.old`.

**Comment by patflynn** [comment]
Specifying a docker directory with a 'java' runtime should be an error.

If the user is using the 'java' runtime, and has a src/main/docker
directory but no configuration of the docker directory in the plugin then
the folder should just be ignored.  Ideally with an info message at staging
time.

**Comment by saturnism** [comment]
Just adding to this, we should ignore Dockerfile completely if runtime is set to java. A warning would suffice though.

**Comment by meltsufin** [comment]
Thinking about this more, I think this logic really belongs in the Cloud SDK `app deploy`. Currently, the plugin doesn't even inspect app.yaml to see if it contains `runtime:java` or `runtime:custom`.

We do have an issue the appengine-plugins-core, where it will throw an exception if the `src/main/docker` directory is empty.

**Comment by patflynn** [comment]
@meltsufin can you follow up and file issues with Cloud SDK and appengine-plugins-core?

**Comment by meltsufin** [comment]
Filed https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/275.
I'm not sure if there's still an issue in gcloud if you specify `runtime: java` and include a `Dockerfile`.

**Comment by loosebazooka** [comment]
in next release.
